kaltura/mwEmbed

- kWidget/kWidget.js
get correct widget element height
> SUP-3480 -- fix hide widget element height

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
hide poster until image is loaded
> SUP-2937 -- hide poster until image is loaded

- modules/KalturaSupport/components/related/related.css
> FEC-2373 #comment add css styles for undealt with screens #time 2d

- modules/DoubleClick/resources/mw.DoubleClick.js
the second part of the fix. javascript side
> FEC-2397 #comment call appropriate method upon pause/resume ad #time 1d

- modules/KalturaSupport/components/sideBarContainer.js
Clear timeout when mouse enters or when reminder button is clicked
> FEC-2582 #comment Fix sidebar hovering mode #time 1h

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
add referrer when we don't have KS as well
> SUP-3502 #time 2h #comment add referrer when we don't have KS as well

- modules/KalturaSupport/components/chapters/chapters.js
Trims whitespace from left and right
> FEC-2635 #comment Trim search expression #time 1h

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/KalturaSupport/components/sideBarContainer.js
Set height of sidebar to take in consideration top and bottom bars.
While sidebar is open - freeze component hover
> FEC-2587 #comment Sync sidebar and top/bottom bars display #time 4h

- modules/KalturaSupport/components/playlistAPI.js
don't redraw the playlist on resize event on iOS8
> FEC-2650 -- don't redraw the playlist on resize event for IOS8

- modules/FreeWheel/resources/mw.FreeWheelController.js
> FEC-2652 -- remove poster when ad start

- modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
- modules/KalturaSupport/components/logo.js
- modules/KalturaSupport/components/share/share.js
I need this merge for the iOS submission
> #FEC-2658 #comment replace the way of nativeAction called

- modules/KalturaSupport/components/playlist/playList.css
set text align of onPage playlists to left.
> SUP-3485 -- Set text align of onPage playlists to left.

- modules/KalturaSupport/resources/mw.KAdPlayer.js
removed redundant adClickPostFix from event name (already set before this line)
> FEC-2783 -- removed redundant adClickPostFix

- modules/KalturaSupport/KalturaSupport.manifest.php
removed plugin property from manifest
> FEC-2776 -- Removed plugin property from manifest

- kWidget/onPagePlugins/onPagePlugins.manifest.php
add onPageJs1 property to Studio configuration
> FEC-2105 -- Add onPageJs1 property to Studio configuration

- modules/KalturaSupport/resources/mw.KBaseMediaList.js
fix layout for vertical onpage with targetId
> FEC-2752 -- fix layout for vertical onpage with targetId

- modules/KalturaSupport/KalturaSupport.php
- modules/KalturaSupport/components/playlist/playList.css
- modules/KalturaSupport/components/playlist/playList.tmpl.html
- modules/KalturaSupport/components/playlistAPI.js
Playlist enhancements:
1. Add dotdotdot to add "..." to long descriptions. Add ellipsis class to titles
2. Support MinClips Flashvar in horizontal playlist
> Playlist enhancements

- modules/KalturaSupport/components/playlistAPI.js
- modules/KalturaSupport/resources/mw.KWidgetSupport.js
reset streamerType for each entry according to the original streamerType Flashvar (if specified)
> FEC-2747 -- reset streamerType for each entry

- modules/KalturaSupport/KalturaSupport.i18n.php
- modules/KalturaSupport/components/sideBarContainer.js
Add ability to set it via config
> FEC-2737 #comment Change default toggle btn title #time 1h

- modules/Kontiki/resources/mw.Kontiki.js
- Fixed Kontiki race condition between plugin load and kontiki agent response. Kontiki plugin will now wait for the Kontiki agent to respond before letting the player continue loading (asyncInit: true). Default timeout is set to 2 seconds.
- Explicitly set `document` when writing proxy swf.
- Added additional logging.
@itaykinnrot,
Please review and merge. Then we need to cherry pick it into 2.22.1
> Kontiki plugin fixes

- modules/KalturaSupport/components/playlistAPI.js
respect user defined mediaItemWidth (drop responsive logic in that case)
> SUP-3641 -- respect user defined mediaItemWidth

- kWidget/onPagePlugins/omnitureOnPage/resources/omnitureOnPage.js
https://na5.salesforce.com/5007000000kbfho
> Omniture tracking issue

- modules/KalturaSupport/resources/mw.KApi.js
- modules/Omniture/resources/mw.Omniture.js
Other plugins to consider:
Doubleclick
FreeWheel
NielsenCombined
Subply
> Cache Kaltura API calls

- modules/EmbedPlayer/resources/mw.MediaElement.js
remove source flavor from the sources array unless its the only available flavor
> FEC-2803 -- remove source unless its the only available flavor

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
Wait for duration before seek on android
> FEC-3040 #comment Wait for duration before seek on android

- modules/EmbedPlayer/resources/mw.MediaElement.js
If playable sources are passed in options then only take them
inconsideration when filtering results based on rules.
> FEC-2682 #comment Filter sources only from playable sources

- modules/KalturaSupport/resources/mw.KDPMapping.js
- modules/Widevine/resources/mw.Widevine.js
> #PLAT-2401 #comment added version number for native sdk player

- modules/KalturaSupport/resources/mw.KAdPlayer.js
run VPAID flow regularly when the ad is an overlay on mobile device
> FEC-3115 -- run VPAID flow for overlay on mobile

- modules/KalturaSupport/components/chapters/chapters.tmpl.html
The change from 1 digit to 2 digit number was wrong
> Fix enumeration logic of chapters

- mwEmbedLoader.php
This pull request expose ```$wgHTML5PsWebPath``` to JavaScript as: ```Kaltura.kWidgetPsUrl```.
Useful for PS plugins. @eitanavgil 
@itaykinnrot 
Please merge
> Expose kWidget-PS base URL

- modules/KalturaSupport/components/playlistAPI.js
set mobilePlayed to true when the user clicks on an entry
> FEC-3130 -- set mobilePlayed to true when the user clicks on an entry

- modules/KalturaSupport/kalturaIframeClass.php
> Revert "#SUP-3568 #comment fix iframe title to entry name #time 3h"

- modules/KalturaSupport/components/dualScreen/dualScreen.js
Fix screen location and dimensions drift when toggling full screen or screen orientation(mobile)
> FEC-2744 #comment Fix screen location and dimensions drift

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
remove timeStamp from WebVTT caption
> remove timeStamp from WebVTT caption

- modules/KalturaSupport/resources/mw.KBaseScreen.js
This pul request adds support for toggling screen of  ```KBaseScreen``` based plugins.
It allows to:
```js
player.sendNotification('toggleScreen', 'share');
```
Please review & merge
> Support for toggling screens using events

- modules/KalturaSupport/components/live/liveCore.js
- modules/KalturaSupport/tests/LiveStreamThumbnailWhenOffline.html
Thumbnail at the end of a live stream FIXED
> SUP 3684 ThumbnailAtTheEndOfLive

- modules/KalturaSupport/components/live/liveStatus.js
FEC-2461 #time 2h #comment OnAir/Offline label now doesn’t behave as
button.
> FEC-2461 fixed

- modules/EmbedPlayer/resources/mw.MediaElement.js
- modules/KalturaSupport/tests/FlavorSelector.preferedFlavorBR.qunit.html
assigned to Michael D. for review
> SUP 4213 preferedFlavorBR

- modules/KalturaSupport/components/streamSelector.js
Use combination that doesn’t prevent user input
> FEC-3401 #comment Fix keyboard binding

- modules/QnA/resources/qna.css
- modules/QnA/resources/qna.js
- modules/QnA/resources/qnaModule.js
- modules/QnA/resources/qnaService.js
> Q and a plugin2 webc493 & webc476

- modules/QnA/resources/qna.css
- modules/QnA/resources/qna.tmpl.html
- modules/QnA/resources/qnaKOExtensions.js
- modules/QnA/resources/qnaModule.js
- modules/QnA/resources/qnaService.js
- modules/QnA/tests/QnA.html
Show the questions the user asked
> Q and a plugin2 webc 507

- modules/MultiDRM/MultiDRM.loader.js
Use html5ps to get the relative path to the dash libs in PS
> FEC-3483 #comment load dash lib relative to player path

- modules/MwEmbedSupport/mediawiki/mediawiki.UtilitiesTime.js
@itaykinnrot @OrenMe need to merge if we want count down using this code to make sense.
> include % 24 in seconds2Measurements else hours is total hours not -

- includes/MwEmbedResourceLoaderStartUpModule.php
- modules/KalturaSupport/kalturaIframeClass.php
Enable on the fly setting of the kwidget-ps directory
> Pass kwidget PS on non cached config

- modules/KalturaSupport/KalturaSupport.manifest.json
- modules/KalturaSupport/KalturaSupport.manifest.php
- modules/KalturaSupport/components/sourceSelector.js
- modules/KalturaSupport/tests/FlavorSelector.preferedFlavorBR.qunit.html
> FEC-2412 Support configuration on flavor selector to display bitrate instead of size

- docs/api_uivars.php
- kWidget/kWidget.js
- modules/KalturaSupport/tests/ThumbnailEmbedExternalThumbnail.html
Also added a test page with example.
> #SUP-4998 #comment add thumbEmbed external thumbnail support #time 2h

- docs/api_evaluates.php
- modules/AdSupport/tests/AdTagUrlSubstitutions.html
- modules/KalturaSupport/resources/mw.KDPMapping.js
* flashVersion
* playerVersion
* player width, height & parent page position.
> ads and documents some simple properties for ad tag urls:

- modules/KalturaSupport/components/live/liveCore.js
FEC-3638 iPad iOS8 - player does not indicate Live if open before start
streaming - FIXED
> FEC-3638 fix

- LocalSettings.KalturaPlatform.php
- includes/DefaultSettings.php
- modules/KalturaSupport/RequestHelper.php
Enable overriding via kconf settings
> Set embed services enabled by default

- modules/KalturaSupport/EntryResult.php
Currently only supported if set in flashvars
> SUP-4886 #comment Support disableEntryRedirect from uiconf

- includes/DefaultSettings.php
- modules/KalturaSupport/components/sourceSelector.js
source selector for Safari hot fix
bump to 2.31.2
> source selector for Safari hot fix

- modules/MultiDRM/MultiDRM.manifest.json
- modules/PlayersJsReceiver/PlayersJsReceiver.manifest.json
- studio/featuresStructure.php
Add Studio support for Embed.ly embeds and Multi DRM plugins
> Add Studio support for Embed.ly embeds and Multi DRM plugins

- .gitignore
- modules/MultiDRM/MultiDRM.loader.js
- package.json
Use npm in order to manage dependencies
> Add default dash player resources

- modules/QnA/resources/css/qna.css
- modules/QnA/resources/qna.js
- modules/QnA/resources/qnaService.js
- modules/QnA/tests/QnA.html
- modules/QnA/tests/config.js
> Q and a plugin2

- modules/Tvpapi/Tvpapi.json
- modules/Tvpapi/resources/getLicenseData.js
- modules/Tvpapi/resources/getLicensedLinks.js
- modules/Tvpapi/resources/getMediaLicenseLink.js
- modules/Tvpapi/resources/tvpapiAnalytics.js
- modules/Tvpapi/tests/tvpapiAnalytics.html
Support for mediaLicenseLink, license data(silverlight, udrm) and
mediaHit/mediaMak
> Add PS modules

- modules/MultiDRM/resources/mw.EmbedPlayerMultiDRM.js
Currently supports only cenc widevine
> FEC-3737 #comment Support dynamic UDRM call buildout

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
Support both external and internal captions together
> TOG-304 #comment Fix OOB and INB captions support

- modules/KalturaSupport/components/scrubber.js
remove tooltip when clicking the scrubber (on mouseup)
> FEC-3666 -- remove tooltip when clicking the scrubber

- modules/KalturaSupport/resources/mw.KCuePoints.js
Allow setting config via flasvars EmbedPlayer.SupportedCuepointTypes
> KMS-7933 #comment Set configurable supported cue point types

- modules/KalturaSupport/components/dualScreen/dualScreenControlBar.css
Use filter option with opacity
> FEC-3949 #comment Fix IE8/9 dual screen control bar gradient

- modules/QnA/resources/qna.js
- modules/QnA/resources/qnaModule.js
1. set interval to null after clearInterval + check if interval is null
before creating
2. try to access window['parent'].document instead of window['parent']
to see if we get an exception
> post review fixes

- kWidget/kWidget.js
- modules/KalturaSupport/tests/ThumbnailEmbedManyPlayers.qunit.html
* not sure why it was there to begin with ? 
* added flower play button override example to thumb Embed page.
> FEC-3904 -- Removed !important in thumb embed css

- modules/DebugInfo/DebugInfo.manifest.php
- modules/DebugInfo/DebugInfo.php
- modules/DebugInfo/resources/DebugInfo.css
- modules/DebugInfo/resources/DebugInfo.js
- modules/DebugInfo/resources/DebugInfo.tmpl.html
- modules/DebugInfo/resources/simpleBindingHelper.js
- modules/DebugInfo/tests/Info.html
> FEC-3629 debug info pannel

- modules/EmbedPlayer/resources/mw.EmbedPlayerKplayer.js
- modules/KalturaSupport/tests/HLS/HLS_Visualisation.html
- modules/KalturaSupport/tests/HLSPlaybackTester.html
> new hls buffer parameters

- modules/EmbedPlayer/binPlayers/nativeBridge.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
- modules/KalturaSupport/components/sourceSelector.js
NativeBridge: Added switchFlavor to playerMethods
EmbedPlayerNativeCOmponent: Added SourceSelector to supported features
SourceSelector: tweak for native -- the flavors are loaded earlier.
> FlavorSelector -- Mobile/Native

- modules/Heartbeat/resources/KalturaVideoPlayerPluginDelegate.js
> FEC-3840 fixed

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/Heartbeat/resources/KalturaVideoPlayerPluginDelegate.js
> FEC-3829 Heartbeat doesn't report bitrate for live streams

- modules/Heartbeat/resources/KalturaVideoPlayerPluginDelegate.js
- modules/Heartbeat/resources/heartbeat.js
- modules/KalturaSupport/resources/mw.KAdPlayer.js
> FEC-3820 - POD info added

- modules/QnA/resources/qna.js
- modules/QnA/resources/qna.tmpl.html
- modules/QnA/resources/qnaModule.js
enter to send a question enter+ctrl|/alt/shift for new line
> WEBC-591 for both new question and in thread reply

- modules/KalturaSupport/components/scrubber.js
back from pause moves the stream to live - Fixed
scrubber still on the live edge for Native - not a regression
> FEC-3975 live DVR on Native player

- modules/QnA/resources/qnaService.js
if u ask for a que point with time +1 you might miss stuff from the
same second
> WEBC-616 bug fix

- modules/DoubleClick/resources/mw.DoubleClick.js
- modules/Heartbeat/resources/heartbeat.js
- modules/KalturaSupport/resources/mw.KAdPlayer.js
> FEC-3820 pod support added for heartbeat analytics

- modules/QnA/resources/css/qna-threads-list.css
- modules/QnA/resources/qna.tmpl.html
- modules/QnA/resources/qnaModule.js
- modules/QnA/resources/qnaService.js
> Qna plugin ui enhancements

- modules/KalturaSupport/tests/ExternalLogger.html
- resources/mediawiki/mediawiki.log.js
add support for custom logger with filter and auto scroll support. Added test page
> External Logger

- kWidget/kWidget.api.js
- kWidget/kWidget.js
- modules/KalturaSupport/kalturaIframeClass.php
- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
@itaykinnrot  this needs to be reviewed and merge to 2.35
> change IE detection so library will be supported in smartClient

- modules/KalturaSupport/components/share/share.js
fix email sharing for cases when there’s no email client
> fix email sharing (TR-194)

- modules/KalturaSupport/resources/mw.KBaseScreen.js
Fix problem in which changeMedia event triggers hideScreen before the template data is ready and hideScreen crashes
> Hidescreen condition enhancement

- modules/ComscoreStreamingTag/resources/mw.ComscoreStreamingTag.js
Fixed an undefined reference when the player is opened as full screen
> Fixing issue with full screen

- modules/ComscoreStreamingTag/resources/mw.ComscoreStreamingTag.js
- modules/ComscoreStreamingTag/tests/ComscoreStreamingTag.html
- modules/ComscoreStreamingTag/tests/test_ads.html
- modules/ComscoreStreamingTag/tests/test_ads_2.html
- modules/ComscoreStreamingTag/tests/test_playlist.html
- modules/ComscoreStreamingTag/tests/test_playlist_ads.html
Remove configuration options
Some fixes for the ComScoreStreamingTag module
Remove usage of eval()
> New version for the ComScoreStreamingTag

- modules/QnA/resources/qnaService.js
- modules/QnA/tests/QnA.html
- modules/QnA/tests/config.js
> WEBC-627 Change the way we treat code cue points in Q&A

- modules/KalturaSupport/resources/mw.KBaseMediaList.js
- modules/KalturaSupport/tests/PlaylistResponsive.html
support percentage in the mediaItemWidth Flashvar
> support percentage in the mediaItemWidth Flashvar

- docs/api_uivars.php
- modules/AdSupport/tests/perUserAgentAds.php
- modules/GoogleAnalytics/tests/GoogleAnalytics.qunit.html
- modules/KalturaSupport/KalturaSupport.manifest.json
- modules/KalturaSupport/components/share/SharePlaylist.html
- modules/KalturaSupport/tests/HLSMultiAudioFlashTest.html
- modules/KalturaSupport/tests/HLSPlaybackTester.html
A few documentation and minor fixes need to be merged into the 2.36 release.
> Sync 2.36 with master

- modules/Chromecast/resources/chromecast.js
send native SDK the chromecast App ID
> send native SDK the chromecast App ID

- modules/ComscoreStreamingTag/resources/mw.ComscoreStreamingTag.js
- Fixing issues with multiple play and pause events.
- Fixing issues with regex.
- Fixing issues with ads.
> - Fixing comScore module

- kWidget/kWidget.js
- modules/KalturaSupport/resources/mw.KalturaIframePlayerSetup.js
null reference causes loading exception
> Fix mobile inlineScript loading

- modules/EmbedPlayer/EmbedPlayer.config.json
- modules/EmbedPlayer/resources/mw.PlayerLayoutBuilder.js
- modules/KalturaSupport/components/controlBarContainer.js
- modules/KalturaSupport/components/currentTimeLabel.js
- modules/KalturaSupport/components/durationLabel.js
- modules/KalturaSupport/components/playPauseBtn.js
- modules/KalturaSupport/components/related/related.css
- modules/KalturaSupport/components/scrubber.js
- modules/KalturaSupport/components/sourceSelector.js
- modules/KalturaSupport/components/topBarContainer.js
- modules/KalturaSupport/resources/mw.ClosedCaptions.js
- modules/KalturaSupport/resources/mw.KBaseSmartContainer.js
- modules/KalturaSupport/resources/uiConfComponents/playbackRateSelector.js
- modules/KalturaSupport/resources/uiConfComponents/titleLabel.js
- modules/MwEmbedSupport/jquery.loadingSpinner/jquery.loadingSpinner.js
- resources/mediawiki/mediawiki.kmenu.js
- skins/kdark/css/icons.css
- skins/kdark/css/layout.css
wrap entire mobile skin new design with a feature flag (Flashvar): "EmbedPlayer.EnableMobileSkin"
> mobile skin new design feature flag

- modules/DoubleClick/resources/mw.DoubleClick.js
- modules/DoubleClick/tests/DoubleClickNoFlash.html
load entry video while ad is playing in JS SDK. Also add test page for JS SDK
> Doubleclick enhancements

- modules/EmbedPlayer/resources/mw.EmbedTypes.js
- modules/EmbedPlayer/resources/mw.MediaPlayers.js
- modules/MultiDRM/MultiDRM.loader.js
The native SDK uses window.kNativeSDK.supportedFormats.
> FEC-4723 #comment Allow native SDK to specify supported formats.

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/KalturaSupport/components/live/liveCore.js
- modules/KalturaSupport/components/live/liveStatus.js
- modules/KalturaSupport/components/scrubber.js
new DVR layout (liveEdgeOffset)
> FEC-4777-liveEdgeOffset

- modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
Add support for stpo/continue after seek via config option.
Use triggerHelper for triggering events from the youtube wrapper.
Use YT state enum object.
> FEC-4786 #Support seek options on youtube player

- skins/kdark/css/layout.css
- skins/ott/css/layout.css
Replace dotted frame to line frame in browsers
Remove selection on mobile devices
> Fix FEC-4868

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
set the error message in the player (was missing)
> FEC-4873 #comment 

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
> reverse to previous seek accuracy

- modules/Quiz/resources/IVQApiCall.js
- modules/Quiz/resources/quiz.js
> KMS-11089 All cue points can be viewed using Widget KS

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
Fixed regression with doubleclick and flash based player
> FEC-4938 #comment Handle clip done when seeking to end of media

- modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
- modules/KalturaSupport/resources/mw.KWidgetSupport.js
Currently only passed to native component
> FEC-5098 #Integrate FPS DRM data from backend service

- modules/KalturaSupport/components/share/share.css
fix share alignment: align icons to center. Also did some cleanup in share css
> fix share alignment

- modules/EmbedPlayer/resources/mw.EmbedPlayerKplayer.js
- modules/KalturaSupport/components/dualScreen/displays.js
- modules/KalturaSupport/components/dualScreen/dualScreen.js
- modules/KalturaSupport/components/dualScreen/videoPlayer.js
Big screen will always play AUTO (-1)
Small screen will always play lowest bitrate
> ABR sollution

- modules/KalturaSupport/components/share/share.js
- modules/KalturaSupport/resources/mw.KBaseScreen.js
> SUP-7442 add getScreen when player is ready to KBaseScreen

- modules/KalturaSupport/components/dualScreen/dualScreen.css
> SUP-6501 Capturespace presentation ratio

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
> SUP-6927 Keep poster if Audio player

- modules/KalturaSupport/components/dualScreen/dualScreen.css
> SUP-6501 Capturespace presentation ratio fix

- modules/DoubleClick/resources/mw.DoubleClick.js
> cherry pick https://github.com/kaltura/mwEmbed/pull/2379/files

- modules/Quiz/resources/IVQModule.js
> Revert "KMS-11206 question skipped and wasn't jumped up"

- modules/KalturaSupport/components/related/related.js
@OrenMe moved square layout fix from https://github.com/kaltura/mwEmbed/pull/2537 to 2.43
> #SUP-7026 #comment moved fix to 2.43

- modules/EmbedPlayer/resources/mw.MediaElement.js
> SUP-7573 Check videoElement BlackVideoSources on mobile with Thumb embed

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
> SUP-6927 KeepPoster on autoPlay if audio entry

- modules/EmbedPlayer/resources/mw.EmbedPlayerKplayer.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/Hlsjs/resources/hlsjs.js
- modules/KalturaSupport/resources/mw.id3Tag.js
> FEC 5115 id3Tag hlsjs

- modules/MultiDRM/MultiDRM.loader.js
@noamtamim - need to change this to not enhance the prototype at all…
> FEC-5524 #comment Fix array prototype change crash DRM lib

- modules/DoubleClick/resources/mw.DoubleClick.js
will move to relevant branch once it is opened.
> SUP-7515 set the volume after each ad loaded event

- docs/api_uivars.php
- modules/KalturaSupport/resources/mw.KCuePoints.js
> SUP-6103 fix plural in ui var - thumbnails to thumbnail

- modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
If supplied via flashvar. If not, build the udrm url as usual.
> FEM-487 overrideDrmServerURL for online playback

- modules/EmbedPlayer/resources/mw.EmbedPlayerKplayer.js
> Sup 8326 fix server speed playback for chrome and FF

- modules/KalturaSupport/kalturaIframeClass.php
added forceCompatMode flashVar to passthrough IE compat meta tag
> example fix for SUPPS-686 (TR-885)

- resources/MwEmbedSharedResources.json
- resources/polyfills/Array.filter.js
- resources/polyfills/Array.findIndex.js
- resources/polyfills/Array.forEach.js
> PolyfillsSupport

- modules/Hlsjs/resources/hlsjs.js
> Check if hlsjs was actually loaded before cleaning up

- modules/KalturaSupport/KalturaSupport.json
- modules/MultiDRM/MultiDRM.loader.js
- modules/MultiDRM/resources/mw.FPS.js
> Add support for Safari desktop FPS

- modules/KalturaSupport/KalturaSupport.json
- resources/MwEmbedSharedResources.json
> Fix naming convention issue with polyfills

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
- modules/MultiDRM/MultiDRM.loader.js
> Add support for OTT FairPlay

- modules/Chromecast/resources/chromecast.js
- modules/Chromecast/resources/mw.EmbedPlayerChromecastReceiver.js
- modules/Chromecast/resources/receiver/mpl.js
- modules/Chromecast/resources/receiver/receiver.html
- modules/Chromecast/tests/ChromecastDemo.html
- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/EmbedPlayer/resources/mw.PlayerLayoutBuilder.js
- modules/KalturaSupport/components/largePlayBtn.js
- modules/MwEmbedSupport/jquery.loadingSpinner/jquery.loadingSpinner.js
- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
- skins/kdark/css/layout.css
* make sure the player ui is visible
* add default configuration to the chromecast UI based on mobile skin
* change the largePlayBtn to TV mode (show pause when paused)
* add option to pass different uiconf to the chromecast plugin
> Chromecast ui/x

- modules/KalturaSupport/kalturaIframeClass.php
> #SUP-8163 remove black pixel poster

- modules/KalturaSupport/components/related/Related.html
- modules/KalturaSupport/components/related/related.js
> #SUP-6410 Related plugin clickUrl modification to open in new tab

- includes/DefaultSettings.php
> Support overriding kwidget-ps location from LocalSettings

- modules/Chromecast/resources/chromecast.js
> Wait for chromecastplayer to load

- modules/DoubleClick/resources/mw.DoubleClick.js
> Make sure IMA is loaded in chromecast

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
> SUP-8648 add flag to sort captions alphabetically

- modules/KalturaSupport/apiServices/mweApiGetLicenseData.php
This includes the fpsCertificate, if available.
> Added FairPlay offline support to the GetLicenseData service.

- modules/KalturaSupport/components/controlBarContainer.js
- modules/KalturaSupport/components/info/info.js
- modules/KalturaSupport/components/related/related.js
- modules/KalturaSupport/components/share/share.js
> SUP-8725_HoverControls_components_UX_fix

- modules/Chromecast/resources/chromecast.js
- modules/Chromecast/resources/mw.EmbedPlayerChromecastReceiver.js
- modules/Chromecast/resources/receiver/mpl.js
- modules/Chromecast/resources/receiver/receiver.html
Remove redundant loading of jQuery and Google font from receiver
Hide the player interface until video loads
Get player to register to video tag events only after media loads
Force auto play
Remove cache busting of player library
> enhance chromecast receiver performances

- modules/MultiDRM/resources/mw.FPS.js
> Set correct uDRM request header

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/EmbedPlayer/resources/mw.FullScreenManager.js
- modules/KalturaSupport/components/live/liveCore.js
- modules/KalturaSupport/components/playlistAPI.js
- modules/MultiDRM/resources/mw.EmbedPlayerMultiDRM.js
- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
Fix issues for the next tickets:
FEC-5919
FEC-5904
FEC-5893
FEC-5892
FEC-5887
> iOS 10 compatibility fixes

- modules/Chromecast/resources/chromecast.js
- modules/Chromecast/resources/mw.EmbedPlayerChromecast.js
- modules/Chromecast/resources/mw.EmbedPlayerChromecastReceiver.js
- modules/Chromecast/resources/receiver/mpl.js
change media using the source selected on the receiver
> Chromecast change media refactor

- modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
> Remove redundant call to setup readyCallback only once

- modules/Chromecast/resources/chromecast.js
- modules/Chromecast/resources/receiver/mpl.js
- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
- modules/KalturaSupport/components/largePlayBtn.js
fix change media and replay issues
> fix change media and replay issues

- modules/DoubleClick/resources/mw.DoubleClick.js
> Continue playback flow after ad error when autoplay is set

- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
> FEC-5966 FEC-6004 #comment

- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
> Revert "FEC-5966 FEC-6004 #comment"

- modules/KalturaSupport/components/theme.js
> SUP-8778 reduce left and right buttons margins for IE

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
- skins/ott/css/layout.css
> Fix "responsive" closed captions on fullscreen open/close

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> Set preload to auto without any condition when play is clicked

- modules/KalturaSupport/EntryResult.php
> Enable fetching more then 500 entries of cue points

- kWidget/kWidget.js
@OrenMe Had to revert the fix from SUP-6313 as it broke the auto player for mobile, now we only call 'doPlay' when on mobile devices.
> Sup 6782 add play only for mobile with thumbnail embed

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
FEC-6043 
FEC-6044 
FEC-6046
FEC-6047
> Call load() explicitly instead of preload attribute

- modules/Hlsjs/resources/hlsjs.js
- modules/KalturaSupport/resources/mw.id3Tag.js
> ADD hlsjs id3 tag sync

- modules/Hlsjs/resources/hlsjs.js
> Fix hlsjs playback selection on changeMedia

- modules/KalturaSupport/resources/mw.KAds.js
After midrol ends, if last location time is bigger than midrol time - continue video from there.
FEC-6090
> Seek video to the last location after midrol

- modules/DoubleClick/resources/mw.DoubleClick.js
> Clear timout of skip btn when changing media

- modules/Dash/resources/dash.js
This reverts commit 0c75d514d133bab86dfb08c4aef998cc026c754a.
> FEC-6129 #comment Re enabling shaka on android

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
> Adding safe check when source equals to -1

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
> Changing isPauseLoading to false on clip done to support large play button after postroll

- modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
> When starting to play video, hide first the blackBoxHide css class

- modules/KalturaSupport/apiServices/mweApiGetLicenseData.php
If flavor_id param is not sent at all, the result licenseUri will not contain a files parameter. If it's empty, it will contain the first available flavor.
> Change to getLicenseData API.

- modules/DoubleClick/resources/mw.DoubleClick.js
> Check if the skipBtn is true or false from double-click plugin

- modules/KalturaSupport/components/theme.js
@OrenMe @amirch1 fix the "Apply drop shadow to icons" since it was not working after the mobile skin was enabled.
> Apply drop shadow to icons

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/KalturaSupport/kalturaIframeClass.php
@OrenMe your fix works like a swiss watch
> SUP-8163 remove the black pixel poster only for iPad

- resources/mediawiki/mediawiki.js
> Exclude Hlsjs module in case of IE8

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/MultiDRM/resources/mw.EmbedPlayerMultiDRM.js
@OrenMe 
Forgot to add the revert for https://github.com/kaltura/mwEmbed/pull/2794
> Revert fix from https://github.com/kaltura/mwEmbed/pull/2794

- modules/Dash/resources/dash.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/Hlsjs/resources/hlsjs.js
- modules/Tvpapi/resources/tvpapiAnalytics.js
* set didFirstPlay to false on changeMedia
* clear parseTextTracksTimeout on changeMedia
* call unbind to seeking and firstPlay separately in order to use the bindPostFix
> FEC-6164 #comment Fix the changeMedia issue

- modules/AdSupport/resources/mw.AdTimeline.js
- modules/DoubleClick/resources/mw.DoubleClick.js
> Issue play also if the ad is not linear

- modules/KalturaSupport/components/nextPrevBtn.js
> Setup nextPrevBtn binding even if not mobile skin and change binding logic

- modules/DoubleClick/resources/mw.DoubleClick.js
> Fix broken companion due to API change on IMA

- modules/DoubleClick/resources/mw.DoubleClick.js
> Exclude playlistAPI from the excludeComponents list

- modules/DoubleClick/resources/mw.DoubleClick.js
> Revert "Exclude playlistAPI from the excludeComponents list"

- modules/DoubleClick/resources/mw.DoubleClick.js
> Pause skip timout when ad is paused

- modules/Peer5/Peer5.manifest.json
- modules/Peer5/resources/mw.Peer5.js
- modules/Peer5/tests/Peer5.qunit.html
This is a change needed as part of the integration simplification.
(supersedes older PRs)
> peer5 plugin update

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/MultiDRM/resources/mw.EmbedPlayerMultiDRM.js
@OrenMe  @yairans made the change to load only when using iPad
> Sup 8825 fix i os flavor transition

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
> Add flag to force high res flavour selection for HLS

- modules/DoubleClick/resources/mw.DoubleClick.js
> Fix playlist with ads get stuck on changeMedia

- modules/DoubleClick/resources/mw.DoubleClick.js
> Resume skip timeout only if ad is not skippable 

- modules/KalturaSupport/components/info/info.css
- modules/KalturaSupport/components/info/info.tmpl.html
@OrenMe this was a feature request that Karin confirmed the change.
> SUP-9527 change the views to plays in the info plugin

- studio/featuresStructure.php
1. Add "Update Version Automatically" checkbox in Studio basic settings
2. Add tooltip for this feature
> FEC-5936: support latest player version in Studio

- modules/KalturaSupport/KalturaSupport.i18n.json
> SUP-9063 changed the slideLocator tooltip text

- modules/KalturaSupport/resources/uiConfComponents/moderationPlugin.js
Need to refactor to be fully compliant with baseScreenPlugin
FEC-6231
> Emit screen events for moderation plugin

- modules/Dash/resources/dash.js
- modules/Hlsjs/resources/hlsjs.js
> SUP-9515 Change delivery protocol to http on player load

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
> Reset closedCaptions UI state on media change

- modules/DoubleClick/resources/mw.DoubleClick.js
> Change default IMA3 companion ResourceType to ALL

- modules/DoubleClick/resources/mw.DoubleClick.js
Fix ads does not work due to escaping which is not required done at web side
> dfp-does-not-work-escaping-issue

- modules/Dash/resources/dash.js
- modules/Hlsjs/resources/hlsjs.js
- modules/KalturaSupport/components/sourceSelector.js
@OrenMe  made the relevant changes to not use switch on resize with adaptive.
> Sup 9515 change delivey protocol on player load

- modules/DoubleClick/resources/mw.DoubleClick.js
@OrenMe made the relevant change
> SUP-9982 Change default IMA3 companion CreativeType to ALL

- modules/KalturaSupport/components/dualScreen/displays.js
@OrenMe deleting the two lines is the same as the switch, let me know if you want me to change the PR.
Thanks
> SUP-9824 Revert display toggle in SbS view

- modules/Hlsjs/resources/hlsjs.js
> Turn off goingBackToLive flag only after seek ends

- modules/Hlsjs/resources/hlsjs.js
> Seperate turning off goingBackToLive between DVR case and non DVR case

- modules/Hlsjs/resources/hlsjs.js
> hlsjs - Force change level when auto is enabled

- modules/Hlsjs/resources/hlsjs.js
> hlsjs - Force change level when auto is enabled or while level is switching

- modules/KalturaSupport/resources/uiConfComponents/playbackRateSelector.js
> Revert "Change playbackrate api in playManifest request"

- modules/KalturaSupport/components/dualScreen/dualScreen.js
> SUP-9827 Update dual screen state for audio entry

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
@OrenMe This fixes the issue for Chrome, FF and Safari. IE still has the issue and will be handled in a separate Jira.
> SUP-10007 add auto language direction to CC trackWindow

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> Change location of addBindings method in EmbedPlayerNative

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
Currently only if multiDrm plugin is enabled
Supports HLS FPS, Dash CENC and SmoothStream PlayReady
> Add Live DRM support

- modules/Dash/resources/dash.js
> Add default Widevine CDM Robustness level

- modules/KalturaSupport/kalturaIframeClass.php
> SUP-9286 Player Button size not saved on Android and iPad

- modules/KalturaSupport/resources/mw.KBaseMediaList.js
> SUP-9661 playlist player with Iframe embed not playing

- modules/Dash/resources/dash.js
- modules/Hlsjs/resources/hlsjs.js
> Support setting default audio track

- modules/DoubleClick/resources/mw.DoubleClick.js
> Resume ad if it paused while skipping it

- modules/DoubleClick/resources/mw.DoubleClick.js
> Clear adSkip timeout when skipping from paused ad

- modules/Dash/resources/dash.js
> Set DRM robustness level only on Chrome

- skins/kdark/css/layout.css
fix size and layout of mobile skin controls for very small players ("size-tiny" class on player main DIV)
> KMCNG-196 Small players controls size & layout fixes

- modules/KalturaSupport/components/dualScreen/dualScreen.js
@OrenMe as discussed to limit of the draggable area will be handled by Vlad
> SUP-9113 Limit resizing dimensions for dualScreen

- modules/KalturaSupport/components/adsServerStich.js
Get the click through address from the server response and not hard coded
> get the click through address from server

- modules/AdSupport/resources/mw.AdTimeline.js
> Fix pause video after post roll ends in case no video sibling

- modules/Chromecast/resources/receiver/receiver.html
> Chromecast - change video width and height to 100%

- modules/Hlsjs/resources/hlsjs.js
if we're on android-chrome.
FEC-6537
> Dont issue play on player switch src after postroll 

- modules/KalturaSupport/components/theme.js
@OrenMe the issues is fixed once removing the importent, I checked with all other browsers to see if the removal has any effecte and all is working as expected.
> SUP-9095 IE8 square playhead

- modules/KalturaSupport/resources/mw.KDPMapping.js
> Prevent circular dependency on OTT change media

- modules/Quiz/resources/quiz.js
Default will stay as auto-continue
> Add an option to not auto-continue the quiz after submission.

- modules/Youbora/resources/mw.Youbora.js
> Analytics - Send '-1' as initial bitrate when changing media

- modules/Youbora/resources/mw.Youbora.js
> Analytics - Fix code property duplicate incrementation

- modules/ComscoreStreamingTag/resources/mw.KalturaComScoreSTAPlugin.js
TAG-3069 The trackEventMonitor feature does not work in the new refactored plugin.
TAG-3071 Our Kaltura player plugin is always loaded even when it is not linked.
> Bug fixes:

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/KalturaSupport/resources/mw.KWidgetSupport.js
* Remove duplication of errors reporting by the player.
* Add an error code to each error object creating by the player.
> Youbora reporting fixes

- modules/KalturaSupport/components/related/related.js
> Revert "FEC-6621"

- modules/Youbora/resources/youbora-adnalyzer.js
> Youbora fix - no adPause or adResume when pausing and resuming ad playback

- modules/Youbora/resources/youbora-adnalyzer.js
> Youbora fix - Kaltura bumper is reported as midroll

- modules/Youbora/resources/youbora-adnalyzer.js
> Youbora fix - skip ad is not reported

- modules/Youbora/resources/youbora-plugin.js
> Youbora fix - resume event reported after adJoin

- modules/DoubleClick/resources/mw.DoubleClick.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> Mobile autoplay fixes - phase 1

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> Fix autoplay on ipad - remove 'inline' attr from video element

- modules/KalturaSupport/resources/mw.KAdPlayer.js
> Set volume to 1 when pausing or skipping a bumper

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> Mobile autoplay fix - enable audio on user interaction while ad is play

- modules/Youbora/Youbora.manifest.json
- modules/Youbora/resources/mw.Youbora.js
> Support youbora plugin backward compatibility

- modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
- modules/ExternalPlayers/tests/PlayFromYouTubePlayerIframe.html
* Pass mediaPlayFrom and mediaPlayTo vars to YT player
> KMS-14518 YouTube mediaPlayFrom support

- modules/KalturaSupport/KalturaSupport.manifest.json
Default value set to current default
> Add option to hide source from playback menu

- modules/MultiDRM/resources/mw.FPS.js
> Change media with FPS DRM fails

- resources/MwEmbedSharedResources.json
wrong CSS path caused resource loader to crash
> Fix crash in player loading(FEV-76)

- modules/KalturaSupport/components/chapters/chapters.css
- modules/KalturaSupport/components/chapters/chapters.js
* Add optional 'cssClamp' configuration to enable optimized CSS-only lines ellipsis
* Debounce 'updateLayout' callback
* Optimize 'setMediaBoxesDimensions' performance
> Improve performance on large lists

- modules/KalturaSupport/components/chapters/chapters.js
* Remove last list size check
* Rely on data-box-type attribute instead of DOM index
> SUPPS-11290 webcast regression

- modules/DoubleClick/resources/mw.DoubleClick.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> Fix autoplay issues on Android

- modules/EmbedPlayer/EmbedPlayer.i18n.json
- modules/KalturaSupport/components/audioSelector.js
- modules/KalturaSupport/components/logo.js
- modules/KalturaSupport/components/scrubber.js
- modules/KalturaSupport/components/sourceSelector.js
- modules/KalturaSupport/components/streamSelector.js
- modules/KalturaSupport/components/volumeControl.js
- modules/KalturaSupport/resources/mw.ClosedCaptions.js
- modules/KalturaSupport/resources/mw.KBaseScreen.js
- modules/KalturaSupport/resources/uiConfComponents/moderationPlugin.js
- modules/KalturaSupport/resources/uiConfComponents/playbackRateSelector.js
- modules/KalturaSupport/tests/AccessibilityControls.html
- modules/Quiz/resources/quiz.js
- resources/mediawiki/mediawiki.kmenu.js
- skins/kdark/css/layout.css
This reverts commit d0c0925431d21846f4f306dbfb49b7422dd7d9b2.
> Revert "Accessibility (#3455)"

- modules/DoubleClick/resources/mw.DoubleClick.js
> Register to IMA events only once during playback

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
@OrenMe When using the flashvar with a playlist player the videoDisplay resizes to the entire playlistInterface width, if it is a playlist player I return it to the original size.
> SUP-11548 ForceLayoutRedraw playlist issue

- modules/DoubleClick/resources/mw.DoubleClick.js
> Enable cue points on Android

- modules/KalturaSupport/components/share/share.css
- modules/KalturaSupport/components/share/share.js
- modules/KalturaSupport/resources/mw.KBaseComponent.js
- modules/KalturaSupport/resources/mw.KBaseScreen.js
- modules/KalturaSupport/resources/uiConfComponents/moderationPlugin.js
- resources/mediawiki/mediawiki.kmenu.js
- skins/kdark/css/layout.css
> Accessibility phase 2

- modules/KalturaSupport/components/360/resources/video360.js
@yairans Oren said to add a flag
> SUP-11969 Flag to add EmbedPlayer WebKitPlaysInline with video360

- modules/KalturaSupport/components/chapters/chapters.css
> SUP-11780 boxInfo chapterNumberWrapper covering chapters slider

- modules/Hlsjs/resources/hlsjs.js
> SUP-12118 Auto displayed twice in the source selector

- modules/KalturaSupport/kalturaIframeClass.php
if localization code of 5 char is set - grab only the first 2 
en_US will be en
> locale fix

- modules/KalturaSupport/resources/uiConfComponents/moderationPlugin.js
- skins/kdark/css/layout.css
@eitanavgil Please review PR.
Thanks
> SUP-12109 moderationPluing screen to fit mobile devices

- modules/DoubleClick/resources/mw.DoubleClick.js
change to official IMA SDK url
> Update IMA SDK lib url

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
> SUP-12532-Ads on images will play on HTTP instead of HTTPS

- modules/KalturaSupport/components/logo.js
> FEC-7456 no tooltip for customized logo

- kWidget/kWidget.js
@OrenMe Please review PR, you said this can be fix as a hotfix
> SUP-12735-Fix thumbEmbed vidSrc protocol

- modules/Chromecast/resources/receiver/mw.EmbedPlayerChromecastReceiver.js
> fix(FEC-7491): chrome cast with tokanzeztion is not working

- modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
> fix(FEC-7689): autoplay not working on youtube entries

- modules/Quiz/resources/quiz.js
[IVQ-Access.] continue button keyboard trap
> FEV-136: continue button keyboard trap

- modules/Quiz/resources/quiz.js
[IVQ-Access.] submit and review buttons keyboard trap
> FEV-144 submit and review buttons keyboard trap

- modules/unMuteOverlayButton/resources/css/unMuteOverlayButton.css
> fix(FEC-7740): Auto Play fallback - Unmute button is not working when video playing

- modules/KalturaSupport/components/chapters/chapters.js
- modules/KalturaSupport/resources/mw.KCuePoints.js
- modules/KalturaSupport/resources/webcast/cuePointsManager.js
- modules/WebcastPolls/test/allowAdminCuePoints.html
Hide "admin" slides/chapters/player mode in preview mode
hide for all(without checking flashvar)
> FEV-147 - Hide "admin" slides/chapters/player mode in preview mode

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
- modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
the autoplay restriction has been defered to version 66 of chrome
> fix: do not automute for autoplay on chrome64

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
> fix(SUP-13403): set index of cc off label to last active caption

- modules/DoubleClick/resources/mw.DoubleClick.js
- modules/EmbedPlayer/resources/mw.PlayerLayoutBuilder.js
- modules/KalturaSupport/components/controlBarContainer.js
- modules/KalturaSupport/components/topBarContainer.js
> fix(SUP-13171): adCover blocking VPAID controls

- modules/KalturaSupport/kalturaIframeClass.php
@OrenMe  Please review PR.
Thanks
> fix(FEC-7878): remove support check for windows phone on mobile skin

- modules/Quiz/resources/css/quiz.css
[IVQ-Player] New Q type #2: True/False
> FEV-132 question type True/False

- modules/Quiz/resources/IVQModule.js
- modules/Quiz/resources/css/quiz.css
- modules/Quiz/resources/quiz.js
[IVQ-Player] New Q type #3: Reflection Point
> FEV-131 New Q type - Reflection Point

- modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
> fix(SUP-13280): Mobile skin is blocking the YouTube player play button

- modules/QnA/QnA.i18n.json
Kwebcast - Live event - disable the comments (set EnableQnA as no) display irrelevant message
> SUP-12364-change-message

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
changes to client to support dynamic embed and ECDN
> changes to client to support dynamic embed and ECDN

- modules/Quiz/resources/quiz.js
IVQ: No information and elements when question icon clicked on Submit screen
> KMS-17072-information-screen-after-submit:

- modules/Quiz/resources/IVQModule.js
- modules/Quiz/resources/quiz.js
[IVQ-Editor] new option to remove welcome page
> KMS-16785-remove-welcome-page:

- modules/Quiz/resources/quiz.js
1. when reached reflection point - auto submit it
> FEV-131-auto-submit-reflection-point

- modules/Quiz/resources/css/quiz.css
> FEV-172-align-mid-RP-text:

- modules/KalturaSupport/components/info/info.js
> FEV-152-focus-out-infoScreen

- kWidget/kWidget.js
- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/KalturaSupport/components/share/share.js
@OrenMe Please review for 2.68, also do I need to add the allow attributes here:
https://github.com/kaltura/mwEmbed/blob/e10f52ab7d6eadd2b73a734ee73cfada0ba0b60a/modules/EmbedPlayer/resources/mw.EmbedPlayer.js#L2112
> fix(SUP-13708): Add feature policy to player iframe

- modules/Quiz/resources/css/quiz.css
fix margin between true/false answers
> KMS-17301-true-false-inline-position:

- modules/KalturaSupport/components/live/liveCore.js
@OrenMe  Please review PR.
Thanks
> fix(SUP-12518): Clear interval and timeout on changeMedia event

- modules/KalturaSupport/components/dualScreen/dualScreenControlBar.css
@eitanavgil  Please review PR for 2.68
> fix(SUP-13444): Reduce padding for dualScreen on small embed size

- kWidget/kWidget.js
- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/KalturaSupport/components/share/share.js
> fix(FEC-8162): Add a wildcard to the Policy Controlled Features

- modules/Tvpapi/resources/tvpapiAnalytics.js
> Send mediaHits (location=0) for linear without DVR

- modules/Tvpapi/resources/tvpapiAnalytics.js
@OrenMe - Could you review this please? I found a issue while enabling the flag for MC player hence changed it. Thanks
> tvpanalytics fix bug related to enable nonDvrLinearMediaHits flag

- modules/Dash/resources/dash.js
- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/Hlsjs/resources/hlsjs.js
- modules/KalturaSupport/components/scrubber.js
calculate the start of the DVR window and consider it in scrubber
> fix(FEC-8174): The progress bar growth more than the live stream rolling buffer

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
@OrenMe Fix is intended for 2.70, please review.
> fix(SUP-14288): iOS auto captions not loaded on first launch

- modules/Quiz/resources/quiz.js
@eitanavgil Please review PR.
Thanks
> fix(SUP-14173): Change screen orientation detection

- modules/KalturaSupport/KalturaSupport.i18n.json
- modules/KalturaSupport/components/chapters/chapters.js
add correct tabindex and aria label. and keydown even
> FEV-184-chapter-side-menu-buttons-new:

- modules/Quiz/Quiz.i18n.json
- modules/Quiz/resources/css/quiz.css
- modules/Quiz/resources/quiz.js
1. fix keyboard tab order of cp and submit button
2. add aria-label
3. fix click issue with continue button on "almost done" screen
> FEV-182-submit-button-new:

- modules/KalturaSupport/components/live/liveStatus.js
@OrenMe Fix is intended for 2.70, please review.
> fix(SUP-14115): Reset liveStatus button state on changeMedia

- modules/KalturaSupport/resources/mw.KAnalytics.js
- modules/KalturaSupport/resources/mw.kAnalony.js
> Sup 13983 reports seem to be inaccurate update

- modules/QnA/resources/qna.js
@eitanavgil Please review my PR
> fix(sup-14444): addressed the matter with the hidden QnA div on VOD

- modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
> fix(SUP-14542): Fix the Unmute button support for live entires

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> fix(SUP-14115): added a protection DVR on seek-able length

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
- modules/KalturaSupport/tests/ClosedCaptions.html
> KMS-17000 - support FE filtering captions by displayOnPlayer

- modules/QnA/resources/qna.js
@eitanavgil please review this PR
> fix(sup-14444): the qna div should not be seen on live

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
> fix(SUP-13922):entry is playing audio only in edge when on embedframe

- modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
> fix(sup-14636):address the matter with the unmute button in mobile

- modules/Chromecast/resources/sender/chromecast.js
@OrenMe Please review my PR.
Fix:
1. DOM selector was unable to access the 'top' event.
2. Added the docContext.
> fix(sup-14798): fixed the issue with chrome cast in Iframe

- resources/mediawiki/mediawiki.js
include the partner Id on the `load.php` request so we have widget or partner id on any request.
format is `partnerId=1234`
> feat(FEC-8085): send the partner id on all player requests

- modules/KalturaSupport/components/dualScreen/dualScreenControlBar.css
@eitanavgil please review my PR
> fix(sup-14594): addressed the matter with information button.

- modules/QnA/resources/qna.js
@eitanavgil Please review this PR
> Webc 1203 support embedding webcast player with q

- modules/KalturaSupport/KalturaSupport.manifest.json
- modules/KalturaSupport/components/dualScreen/dualScreen.js
- modules/KalturaSupport/components/dualScreen/tests/index.html
@OrenMe  let's talk. 
These 3 parameters were implemented as inner-object and were not overriden by flashvar / uivar / Studio. 
This pull is about exposing these 3 params, and per product request - change default ratio to 16/9 (And yes - they are 100% they want to change this) 
Not sure if I want to leave the current object or not. What do you think is safer?
> Webc 1187 expose dualscreen ratio param

- modules/KalturaSupport/download.php
@OrenMe @itaykinnrot 
Per my discussion with Core devs (Moshe Maor, Erez Gotlib) they have provided me with this fix, it seems that we were missing the following code on the player.
> fix(SUP-15010, SUP-15012): Addressed the matter with files returning 0 bytes when downloaded

- modules/KalturaSupport/components/dualScreen/dualScreenControlBar.css
@eitanavgil Please review this PR
> Sup 14594 information icon not working on small medium size player 2

- modules/DoubleClick/resources/mw.DoubleClick.js
Do nothing on non-fatal error
(revert https://github.com/kaltura/mwEmbed/pull/3638)
> fix(FEC-8456): Black player after 1st ads's video

- modules/KalturaSupport/resources/mw.KWidgetSupport.js
@eitanavgil Per our discussion, we saw that when the loadThumbnailWithKs flashvar applies only to the player "Poster" and not on the other Thumbnail use-cases, for example, Chapters cue point thumbnails.
Please review this PR.
> fix(SUP-15427): loadThumbnailWithKs not applying to all thumbnail use-cases.

- modules/KalturaSupport/components/streamSelector.js
@eitanavgil @OrenMe
Please review this PR.
1. We added a Play function to when the entry is on "Seek" and also when the ChangeMedia is initialized before the play (It seems that the issue stems from the Play Promise as the HTML.readyState is set to 0 on change media).
2. We added the setTime to fulfill the playPromise without breaking the code.
> fix(SUP-14895): hlsjs change media with current time bigger than 0

- includes/Hooks.php
- includes/MwEmbedResourceLoader.php
- includes/resourceloader/ResourceLoader.php
- includes/resourceloader/ResourceLoaderFileModule.php
- includes/resourceloader/ResourceLoaderStartUpModule.php
- load.php
- modules/KalturaSupport/RequestHelper.php
- modules/KalturaSupport/apiServices/mweApiUiConfJs.php
- modules/KalturaSupport/kalturaIframeClass.php
> Revert "Add PHP 7 support"

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/MwEmbedSupport/mediawiki/mediawiki.client.js
- modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
added version detection greater than method for safari
> fix(SUP-15736): autoplay fails on Safari desktop V12

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
check if windows width actually changed.
> fix(FEC-8566): V2 - Playlist - Playlist flashing and control bar with video area moved slowly down

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
@OrenMe please review this PR.
Per our discussion, we just implemented this in here to bypass the setTimeout that is set in mw.KWidgetSupport:
https://github.com/shalommeoded/mwEmbed/blob/5fe2421d638a7f45e91ee07cfe6da72e47310415/modules/KalturaSupport/resources/mw.KWidgetSupport.js#L952
> fix(SUP-15880): Addressed the issue when the AutoPlay doesn't work with AutoMute

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
@OrenMe @itaykinnrot 
Per our F2F, I have removed the **playsinline** check from the **canAutoPlay** function.
> FEC 8608 i os autoplay is not working with plays inline=false configuration

- modules/KalturaSupport/resources/mw.kAnalony.js
1. Join time
2. Buffer start / buffer end events
3. Error event
> feat(FEC-8656): kava updates

- modules/KalturaSupport/components/chapters/chapters.css
@eitanavgil 
please review this PR.
> Fix(SUP-15195): Made the Nano-Slider available in touch screens

- modules/KalturaSupport/resources/uiConfComponents/downloadPlugin.js
the fix that will allow the player to download the source file without defaulting the **flavorParamsId** to 0.
> fix(SUP-16728): Can't download an entry with only a source.

- modules/KalturaSupport/KalturaSupport.json
- modules/KalturaSupport/kalturaIframeClass.php
- resources/fonts/familyLato.css
@OrenMe  @shalommeoded 
The library has its own mechanism of loading CSS from local folders - I do not see any reason to treat this file differently and hard-code the CSS on the main PHP. 
Please tell me what you think of this approach.
> Fix wrong relative fonts path

- modules/KalturaSupport/resources/mw.KDPMapping.js
Added a new token `utility.encoded_referrer_url `which exposes the referrer URL with `encodeURIComponent`.
> feat(SUP-17365): added url encoded for referrer token

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
Fuflied the required play promise when on pause, when the player is seeking.
> fix(SUP-17808): No playback on progressive when changing stream quality  

- modules/Quiz/resources/quiz.js
Open Answer will get saved when clicking on the "Hint" button
> fix( SUP-18477): openAnswer not saved when clicking on the hint button

- modules/Quiz/resources/quiz.js
Just changed the default behavior of the quiz getting replyed when submitting
> fix(SUP-18554): quiz is auto replaying

- skins/kdark/css/layout.css
@eitanavgil @OrenMe 
Need to open up a 2.77 branch.
> fix(SUP-18486): DualScreen plugin is overriding the Share plugin

- modules/WebcastPolls/resources/webcastPolls-large.tmpl.html
- modules/WebcastPolls/resources/webcastPolls-medium.tmpl.html
- modules/WebcastPolls/resources/webcastPolls.css
- modules/WebcastPolls/resources/webcastPollsView.js
> Webc 1334 close poll button on poll error

- modules/Quiz/Quiz.i18n.json
- modules/Quiz/resources/IVQModule.js
- modules/Quiz/resources/IVQScreenTemplate.js
- modules/Quiz/resources/css/quiz.css
- modules/Quiz/resources/quiz.js
- modules/Quiz/tests/Quiz.html
> Fev 293 open question feedback

- modules/Dash/resources/dash.js
- modules/EmbedPlayer/resources/mw.MediaElement.js
don't pass shaka DRM init config for clear media, otherwise Shaka check for DRM systems fails
> fix(FEC-9124): don't init DRM on shaka for clear medias

- modules/Dash/resources/dash.js
- modules/Hlsjs/resources/hlsjs.js
remove filtering from hls as it was never an issue there
changed the way we filter on shaka to use built in methods that only give audio representations languages and not adaptations.
> feat(FEC-9034): don't filter same language audio track

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
We trigged the vid.play() on iOS and caused a replay after the postroll.
> fix(FEC-9241): entry is replaying on IOS after post-roll

- modules/Quiz/resources/quiz.js
@OrenMe @eitanavgil 
Please open up a 2.79 branch.
> fix(SUP-19166): "No Seeking Forward" is not working with YouTube Entries on autoPlay

- modules/Quiz/resources/quiz.js
Issue when a user is selecting an answer and choosing to skip to the next question at the same time, the next Question is skipped.
> fix(SUP-19385): Question is skipped when selecting an answer and using the Skip button

- modules/KalturaSupport/components/streamSelectorUtils.js
Split flavorAsset API call into 2 different calls:
1) get child entries
2) in case if child entries exist - get flavorAsset for child entries
> PLAT-9400 split flavorAsset multi-request

- modules/DoubleClick/resources/mw.DoubleClick.js
Added  `encodeURIComponent` to the `evaluatedValue` on the `cust_params`
> fix(FEC-9305): cust_parm is escaping without decoding

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
- modules/KalturaSupport/resources/uiConfComponents/playbackRateSelector.js
ClosedCaption menu accessibly 
PlaybackRate menu accessibly
> Fev 383 cc && pr menu accessibility

- modules/DoubleClick/resources/mw.DoubleClick.js
Here is the fix of the previous pull
> fix(FEC-9305): ads cust_params encoding broken

- kWidget/kWidget.js
isIpadOs was not recognised on Kwidget.
> fix(FEC-9441): iPadOs is not recognised on kWidget

- modules/Hlsjs/resources/hlsjs.js
> fix(SUP-20040): seek options are not synced

- modules/KalturaSupport/components/streamSelectorUtils.js
This reverts commit aa25a7850e7e827e5ca6bcc15d7a44a69eed82a6.
> Revert "PLAT-9400 split flavorAsset multi-request (#4072)"

- modules/Chromecast/resources/sender/chromecast.js
In some cases the plugin will render when the player is not ready, and will not display
> fix(FEC-9490): ChromeCast toggle button does not appear

- modules/Quiz/resources/quiz.js
Added the button display logic to the Open Q
> fix(FEV-396): Disable the skip button when the question is saved on Open Q

- skins/kdark/css/layout.css
The change was done with the Z-index prioritization.
> fix(FEV-401): Chapters are overlapping Vertical Volume Control

- modules/Quiz/resources/quiz.js
Per Ido, we want to alter the Accessibility method of the display question from Aria-label to aria-labelledby.
> fix(SUP-20146): Accessibility changes to the displayed question

- modules/KalturaSupport/resources/mw.kAnalony.js
@OrenMe per our F2F, we saw that the buffering event is starting due to a wrong event propagation from the native events, and therefore, we haven't had the way to determine when to send the buffering events.
Per the solution, we have implemented a flag that we tell us when the video was playing, and had implemented it on the playing and joining time event if statement and also the buffering firing points.
also we had altered the bindHelper event from `onPlay` to `playing.
I have tested the matter on Live, Live VOD, Playlist with Live and VOD, and VOD.
seems that the matter was fixed and the buffering times are triggering on the appropriate time.
> fix(FEC-9424): player sending buffer event when starting a video

- modules/KalturaSupport/resources/mw.kAnalony.js
* PLAY_REQUEST sent on each play
* NO PLAY_REQUEST and wrong join time when in autoplay
* BUFFER_START not sent and BUFFER_END does
* PLAY/RESUME not sent correctly
> fix(FEC-9424): kanalony measurements tweaks

- modules/KalturaSupport/resources/mw.kAnalony.js
Added an additional flag _mediaChange that will be a condition when sendingAnalytics and will set to true onChangeMedia and will reset to false on resetPlayerflags.
> fix(SUP-20341): analytics showing incorrect media type on changeMedia

- modules/Quiz/resources/IVQModule.js
> fix(KMS-20568): results are not set to gradebook

- modules/Chromecast/resources/sender/mw.EmbedPlayerChromecast.js
I have added the additional condition
> fix(SUP-21004): added the chrome version later than 73 condition

- modules/Quiz/Quiz.i18n.json
- modules/Quiz/resources/css/quiz.css
- modules/Quiz/resources/quiz.js
1. Alfred he Span tags to P, per https://stackoverflow.com/questions/15883778/pausing-in-a-screen-reader-for-accessibility.
2. Changed the UN-ANSWERED to UNANSWERED per Product.
3. Added relevant styling for the P tags.
> fix(SUP-21243): Screen reader issues with IVQ

- modules/EmbedPlayer/resources/mw.EmbedPlayer.js
- modules/Hlsjs/resources/hlsjs.js
- modules/KalturaSupport/resources/mw.kAnalony.js
- modules/KalturaSupport/tests/WatermarkTest.qunit.html
THIS PR covers 2 different features (they both have common functions): 
FEV-474-targetBuffer-support
FEV-472-support-forwardBufferHealth
> feat(FEV-472): support forward buffer health

- modules/Quiz/resources/IVQScreenTemplate.js
- modules/Quiz/resources/quiz.js
> SUP-20818 - add aria-labeled-by to open-question textarea

- modules/Quiz/resources/quiz.js
fix(KMS-20782) cannot submit last reflection point after retake
> fix(KMS-20622) missing quiz bubbles after retake

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/Hlsjs/resources/hlsjs.js
Do not move to online (load/restarting hlsjs) unless the player reaches to offline mode (means it has nothing to play)
> feat(FEC-10005): investigate flow when isLive XHR call fails

- modules/KalturaSupport/kalturaIframeClass.php
Convert single quotes by `ENT_QUOTES` flag
> fix(FEC-10103): escape quotes with htmlspecialchars()

- modules/KalturaSupport/RequestHelper.php
sanitize request helper params
> feat: sanitize request helper params

- modules/KalturaSupport/tests/PlayStopApi.qunit.html
`kdp.sendNotfication` should be `kdp.sendNotification`
> Typo in JS code outputted (as HTML)

- modules/KalturaSupport/components/chapters/chapters.js
- modules/KalturaSupport/components/playlistAPI.js
- modules/KalturaSupport/resources/mw.KBaseMediaList.js
The issue is that thumbnailUrl is set to the first parameter that is declared, just changeing the order resolves this. 
Solves SUP-22436
> fix(SUP-22436): playlist thumb are not loading when loadThumbnailWithKs is set

- modules/KalturaSupport/UiConfResult.php
keep it commented for ansible script that might need to add it for onPrem
> feat(FEC-10004): remove statistics plugin from default

- modules/KalturaSupport/components/info/info.js
- modules/KalturaSupport/components/info/info.tmpl.html
Removed the title attribute from the temp file, and added it later on the bind. 
Solves SUP-20488
> fix(SUP-20488): info screen is broken when adding a link to the description

- modules/KalturaSupport/components/chapters/chapters.css
Removed the capitalization of the first letter, and now it will just display the user's initial input.
This was made by product request.
> feat(SUP-9435): initial letters are getting capitalized

- modules/Quiz/resources/quiz.js
@eitanavgil 
I've made this better instead of just deleted the CSS
> fix(SUP-16764): Quiz.plugin pushes the captions up

- LocalSettings.KalturaPlatform.php
Get partner config from kconf per http/s scheme and if found use it instead of default.
Solves FEC-10337
> feat(FEC-10337): use per partner CDN host config

- modules/KalturaSupport/resources/mw.KAdPlayer.js
Set the vid.volume to 0 if we are on autoPlay
> fix(SUP-24104): Auto play ignores bumper

- modules/KalturaSupport/components/scrubber.js
Added indexTab to the scrubber
> fix(SUP-23162): can't tab to scrubber

- modules/KalturaSupport/resources/mw.ClosedCaptions.js
> fix(SUP-24022): Captions are not showing on non user initiated changeMedia

- kWidget/kWidget.api.js
use `for in` instead of `$.each`
> fix: jquery is missing

- modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
- modules/KalturaSupport/resources/mw.KWidgetSupport.js
Dont show the poster on the video tag for audio entry 
Solves SUP-24927
> fix(SUP-24927): Audio playlist shows distorted poster image

- modules/KalturaSupport/components/cvaa/cvaa.tmpl.html
changed text on "edit custom captions" button to be dynamic, and taken from cvaa.js
> Cvaa - edit custom captions text on button should be dynamic

- modules/Quiz/resources/IVQScreenTemplate.js
- modules/Quiz/resources/css/quiz.css
Changes approved by Ido Achrak
> fix(FEC-11232): wrap open-answer buttons in container

- skins/kdark/css/layout.css
**issue:**
moderation submit button on Player is not WCAG accessibility compliant - contrast between background color to text color is low.
**solution:**
changing bg color of the button to darker shade.
solves FEC-11371
> fix(FEC-11371): moderation submit button on Player is not WCAG accessibility compliant

- modules/KalturaSupport/KalturaSupport.i18n.json
- modules/KalturaSupport/components/chapters/chapters.js
- modules/KalturaSupport/components/chapters/chapters.tmpl.html
- modules/KalturaSupport/components/chapters/slides.tmpl.html
- add description to slides/chapters area label;
- use role "button" to define clickable item
> fix(SUP-28484): make chapters thumbnails actionable
