kaltura/mwEmbed

modules/KalturaSupport/components/dualScreen/dualScreen.js
Live with DVR doesn’t dispatch seek event on going back to live so keep
listening to time update for timeline sync
=> FEC-2600 #comment Sync slides on DVR sync #time 4h

modules/KalturaSupport/components/chapters/chapters.js
In webcasting live mode the mediaitems are added as we go so add them
to the existing list instead of writing over the list
=> FEC-2598 #comment Aggregate new media items for webcasting #time 2h

skins/kdark/css/layout.css
move to the right to prevent circle cropping and remove the !important css directive
=> update scrubber css

kWidget/kWidget.js
Note that issue is more complex as the existence of the player object means we actually don’t clean out the player properly!
=> SUP-4096 #comment Validate destroy player before send notification

modules/KalturaSupport/resources/mw.ClosedCaptions.js, modules/KalturaSupport/tests/ClosedCaptions.html, modules/KalturaSupport/tests/ClosedCaptions.qunit.html
Added the ability to define white-labeled array of languages code (E.G. 'whiteListLanguagesCodes': 'en,es,fr,jp'). This configuration will remove all languages but the ones in this list. If the player did not get this attribute it will not interfere with the logic. 
2 test pages were updated to point to the "instant folgers" and new captions files were uploaded to that entry. I highly recommend QA to use this entry (0_uka1msg4) as the entry for testing Captions languages (and sync as well). 
Without white label: 
http://kgit.html5video.org/pulls/1604/modules/KalturaSupport/tests/ClosedCaptions.html#config%3D%7B%22flashvars%22%3A%7B%22closedCaptions%22%3A%7B%22whiteListLanguagesCodes%22%3A%22%22%2C%22useGlow%22%3Afalse%7D%7D%7D
With white label: …
=> FEC-3132 - white-lable captions languages

modules/KalturaSupport/resources/mw.ClosedCaptions.js
This pull request adds the ability to force the ```ClosedCaption``` plugin to load specific caption by language and trigger event so other plugins can use it.
We have new configuration ```forceLoadLanguage``` configuration.
```
closedCaptions.forceLoadLanguage=en
```
This try to find a caption using the "en" as language key, If found we will trigger (new) ```forcedCaptionLoaded``` event.
**These additions does not change anything in the UI or the behavior of the plugin, everything stays the same.**
@itaykinnrot  
Please review & merge
=> Force caption loading

modules/MultiDRM/resources/mw.EmbedPlayerMultiDRM.js
The player state changed to load-state on initial play (when
autoplaying) and caused custom CSS to hide control bar.
=> TOG-295 #comment Set correct player state on play

LocalSettings.KalturaPlatform.php, includes/DefaultSettings.php
This will enable changing the load script domain.
In order to set the ServiceUrl, CdnUrl or other client side Urls please
use mw.setConfig
=> FEC-3559 #comment Allow override domain for player server

modules/EmbedPlayer/resources/mw.MediaSource.js, modules/KalturaSupport/resources/mw.KWidgetSupport.js, modules/MultiDRM/resources/mw.EmbedPlayerMultiDRM.js
uDRM needs to know which exact flavors were selected for playback from
the available flavors returned to player by contextData request
=> Add support for DRM on the fly flavor selection

modules/KalturaSupport/components/largePlayBtn.js
disable largePlayBtn pause on rollover option in IE8
=> FEC-3755 -- disable largePlayBtn pause on rollover option in IE8

modules/KalturaSupport/resources/mw.KWidgetSupport.js
I was trying to override the Scheduling error message to include the start date for the entry.
```json
{
"strings": {
"OUT_OF_SCHEDULING": "This show is scheduled to start at {mediaProxy.entry.startDate}"
}
}
```
The evaluation for ```{mediaProxy.entry.startDate}``` didn't work because in case of error, we first handle the error and adds the expose the meta data later. 
I just changed the order of things to support accessing this data earlier.
Please review & merge
@itaykinnrot @mdale @eitanavgil
=> Expose entry meta data in case of Access control error

modules/KalturaSupport/resources/mw.KAdPlayer.js
creativedata it's not handling the AdParameters element from VAST XML which results in interactive pre-rolls not working.
=> Fixed creativedata being empty

modules/KalturaSupport/components/sourceSelector.js
The stream is detected as http instead of hls, which causes the source selector not to add flavors to menu.
=> Fix for FEC-3965

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
IE ignores preload attribute and loads the source, don’t set the src
attribute until the user issues a play command.
The doPlay function will take care of the source loading.
=> FEC-3717 #comment Lazy load source on IE

modules/KalturaSupport/resources/mw.KWidgetSupport.js
If access control is set then DRM plugin data exist - so only then
create on-the-fly sources.
For playready, create source only if pre-encrypted doesn’t exist and
drama access control does exist.
=> Only support ABR on-the-fly for DRM protected entries

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
Don’t delete the callback function after first changeMedia, as it cuts
the flow for next changeMedia calls which also effects the seek logic.
The change was tested against PS-1861 ticket which was the reason for
the code that was now deleted and everything seems to work properly
with related/playlists/doublclick changeMedia on iPhone and iPad ios7/8
=> SUP-5573 #comment Fix native player changeMedia flow

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
for youtube - disable player controls only if the player cannot autoplay
=> Fix Youtube play list on mobile getting stuck with disabled player when switching entries

modules/AdSupport/resources/mw.AdLoader.js, modules/AdSupport/resources/mw.VastAdParser.js
ajaxOptions (i.e. enableCORS) are only used for the first vast feed in a request chain. If the vast response contains a Wrapper ad stating to download another vast URL, the enableCORS option is not utilized in that secondary request. Without these options, the initial request might have enableCORS set to true and be able to set permanent cookies, but secondary requests are unable to store permanent cookies.
There is only one global enableCORS config setting, it should be used on all requests.
Fix by passing through the ajaxOptions used in the initial request into the mw.VastAdParser.parse function so that they can be used in secondary vast URL requests initiated from within.
=> Passing through ajaxOptions for Wrapped Vast Feeds

modules/KalturaSupport/components/playlistAPI.js
the description below is related to TR-331:
If the empty playlist error happened, mw.KBaseMediaList.js sets config MinClips to zero (because playlist is empty).
Then, when switching to "Player mode”, redrawPlaylist function is called, and here: https://github.com/kaltura/mwEmbed/blob/5d9e19ee5fff0ad23b595b6a6a508676cdf59856/modules/KalturaSupport/components/playlistAPI.js#L312 when updating mediaItemWidth division-by-zero takes place, so mediaItemWidth now equals Infinity, so all other math operations are screwed up and all this results in the TR-331.
=> fix playlist item bad width (TR-331)

modules/AdSupport/resources/mw.AdLoader.js
(reopening for merge in 2.36-Oct-20)
If the first XML node in a Vast feed is a comment, the getAdFormat function fails to idenitfy the format as 'vast', even when the feed is valid. If ad type is chosen by element name, it should instead only check names if the node is an element.
Example Feed:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="2.0">
<Ad id="1">
...
</Ad>
</VAST>
```
=> Checking for XML Element in Vast ad XML instead of generic node

modules/AdSupport/resources/mw.AdLoader.js, modules/AdSupport/resources/mw.VastAdParser.js, modules/KalturaSupport/resources/mw.KAdPlayer.js
(Re-opened from https://github.com/kaltura/mwEmbed/pull/2167 to fix line endings)
If a vast request chain results in more than one wrapper ad, e.g.
wrapper 1 -> wrapper 2 -> ad
then tracking impressions found on all wrappers mut be sent when the main ad's tracking URLs are called.
But currently only tracking urls found on the final wrapper (e.g. wrapper 2) are being called. This is because the wrapperData variable is cleared each time the mw.VastAdParser.parse function is called, but the function has to be called for each vast response.
Fix - Instead of storing only the last wrapperData, store all previous wrapperData objects in an array, and when setting up tracking URL-calling functionality, loop over all stored wrapperData objects and call each object's respective tracking URLs, not …
=> Allowing Impressions from multiple vast wrappers

modules/KalturaSupport/resources/mw.KAdPlayer.js
The VPAID spec indicates for the `initAd()` function we need to pass a width and height into the unit.  The values here describe the __available ad display area__.
For VPAID 2.0:
> 3.1.2 initAd()
> width: indicates the available ad display area width in pixels
> height: indicates the available ad display area height in pixels
For VPAID 1.0:
> 4.7.2 initAd()
> The player passes a width and height to indicate the display area for the ad.
When working with a JavaScript VPAID unit, the `initAd()` function is correctly called with using the embedPlayer width and videoHolder height:
```javascript
VPAIDObj.initAd( _this.embedPlayer.getWidth(), _this.embedPlayer.getVideoHolder().height(), 'normal', 512, creativeData, environmentVars );
```
However flash is different.  The `initAd()` Function is …
=> Correcting flash VPAID dimensions

docs/api_uivars.php, modules/EmbedPlayer/resources/mw.EmbedPlayer.js
Precision may be different between playback engine so check that
element time is in range of +-0.1 of the requested seek target
=> FEC-4211 #comment Fix seek target verification

modules/AdSupport/resources/mw.AdLoader.js, modules/AdSupport/resources/mw.VastAdParser.js, modules/KalturaSupport/resources/mw.KAds.js
The Kaltura player allows string-substitution on the ad URL:
(see http://knowledge.kaltura.com/integrating-kaltura-vast-adtag-url)
If that ad url is a vast wrapper feed, it will contain another URL that should be requested and followed.  But there is no substitution that occurs on these subsequent wrapper vast feeds, meaning each original request also has to contain all parameters for subsequent feed request.
Instead, it will be more useful to allow the same string substitution on Wrapper URLs, so that previous URLs in the vast request chain do not have to pass along all information, and can take better advantage of caching.
Fix: 
Instead of declaring `mw.AdLoader` as a static object, allow it to be initalized similar to `mw.KAdPlayer` - making the object a function where the …
=> Allow Vast Wrapper URLs to work with Kaltura Ad Tag Substitutions

modules/KalturaSupport/components/logo.js
In IE 10/9 width height added, seems like jquery added them to fix aspect ratios.
You can still set width/height using css if required.
=> #SUP-6057 #comment remove width/height IE issue #time 2h

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
Only in case readyForVideo check is in motion, so we mask the event
propagation, so this is to ensure that other check will resume the
event propagation if they are reached before.
=> FEC-4394 #comment Resume event propagation after canSeek check

includes/DefaultSettings.php, modules/KalturaSupport/apiServices/mweApiGetLicenseData.php
Returns a json object with license data (custom_data and signature) for each flavor of a given entry id. Also returns license server base url.
=> FEC-4433 Added new API service: getLicenseData.

modules/ComscoreStreamingTag/resources/mw.ComscoreStreamingTag.js
The evaluateString string function was doing a regex replacement evaluating the wrong parameter.
=> Fix for evaluateString in the ComScoreStreamingTag module

modules/KalturaSupport/KalturaSupport.manifest.json, modules/KalturaSupport/components/nativeCallout/nativeCallout.js
Removed old configuration values. Changed the way callout is opened and the way we show the "app not installed" info.
Config keys removed: storeUrl, mimeName, iframeUrl.
Config keys added: androidApplinkBaseURL, iosApplinkBaseURL, appInstallLandingPage.
=> FEC-4484 Improved the JS side of NativeCallout.

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
start monitor on native onplay event instead of when clicking our play button. Fix for iPhone not restoring monitor after pause in native video player.
=> start monitor on native onplay event

modules/DoubleClick/resources/mw.DoubleClick.js
When we load an empty player with no entry data then we don’t choose a
playback engine, so first check if playback engine is available before
subscribing on DFP events
=> Fix DFP crash on empty player init

kWidget/kWidget.js, modules/EmbedPlayer/resources/mw.EmbedTypes.js, modules/EmbedPlayer/resources/mw.MediaPlayers.js, modules/MultiDRM/MultiDRM.loader.js
Instead of directly injecting window.kNativeSDK.supportedFormats into the webview from native code, pass the same information on the URL's fragment section.
The fragment is parsed in kWidget.js, which expects
#nativeSdkDrmFormats=dash,wvm&nativeSdkAllFormats=dash,mp4,hls,wvm
It then sets window.kNativeSdk.drmFormats and .allFormats with the matching mime types.
=> FEC-4723 #comment Better and safer way of passing supported formats.

modules/KalturaSupport/apiServices/mweApiGetLicenseData.php
In addition,
1. flavor_id (not ids) is now a required parameter, added to the license uri
2. response only includes the requested flavor, not all flavors.
=> FEC-4741 #comment mweApiGetLicenseData: Support OTT systems.

modules/DoubleClick/tests/DoubleClickAdEvents.qunit.html, modules/DoubleClick/tests/DoubleClickCompanionsAutomaticFlashHLSContent.html, modules/DoubleClick/tests/DoubleClickCompanionsManual.html, modules/DoubleClick/tests/DoubleClickManagedForceFlash.qunit.html, modules/DoubleClick/tests/DoubleClickManagedPlayerAdApi.qunit.html, modules/DoubleClick/tests/DoubleClickNoticeMessage.html, modules/DoubleClick/tests/DoubleClickPlaylist.html, modules/DoubleClick/tests/DoubleClickSkipLocale.html, modules/DoubleClick/tests/DoubleClickStreamerType.html, modules/DoubleClick/tests/DoubleClickUseFlash.html, modules/DoubleClick/tests/DoubleClickVPAID.html
Also remove leadWithFlash: false as we now lead with Javascript. Created a test page with leadWithFlash: true to show forcing usage of the IMA Flash SDK
=> remove "path" Flashvar from demo pages

modules/QnA/resources/qnaService.js
when we do a multi request with 1 request in it, and the player calls
startWidgetSession inside we get a single object and not an an array,
so this needs to be changed
=> bug fix for WEBC-3728

modules/DoubleClick/resources/mw.DoubleClick.js
cache ima sdk for future use. Cache busting is done by doubleclick using the request headers
=> cache ima sdk for future use.

modules/Youbora/resources/mw.Youbora.js
MSE based playback holds blob urls in src so they aren’t useful anyhow
=> OPF-4120 #comment Report play manifest URLs always

modules/KalturaSupport/components/sourceSelector.js
Smooth stream medias are loaded with preload true meaning that they
will always load the manifest with bitrates before play.
Always let smooth stream create the bitrate menu.
=> FEC-5444 #comment Fix Smoothstream source selector menu population

modules/KalturaSupport/components/audioSelector.js
-1 option is to inform playback engines not to try and set default on
load (happens in silverlight player)
=> FEC-5482 #comment Set the default to 0 if non is selected

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
The issue is related to a new API Chrome has introduced on v50. The new
HTMLMEDIAELMENT now returns promises.
Currently the solution to this bug is to remove a redundant load method
in the player but need to keep track regarding this change as there are
many open issue around the web, and also a related chromium bug:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&
uact=8&ved=0ahUKEwjp34Wk1e_MAhWCtBoKHQQRAB8QFggiMAE&url=https%3A%2F%2Fbu
gs.chromium.org%2Fp%2Fchromium%2Fissues%2Fdetail%3Fid%3D593273&usg=AFQjC
NFedgog_DYcjvQ7BfEhHKwxEGqEow&sig2=Q0hHOQe9fx0GbZLkEr5OQg&bvm=bv.1224484
93,d.d24
=> FEC-5595 #comment Fix stuck after mid roll ads in Android

kWidget/kWidget.storage.js
Avoid throwing exceptions when API is not available, for example when
machine policy prohibits it and just referencing window.localStorage
crashes
=> Add localStorage is supported check

modules/KalturaSupport/components/streamSelector.js
Tested with CaptureSpace entry, works fine, i.e the stream selector is there.
=> SUP-8323 stream selector specify base entry type to be only MEDIA_CLIP

modules/Hlsjs/resources/hlsjs.js
Issue occurs only on IE11(Win8.1/10) when playing live with autoplay
set to true.
FEC-5800
=> Fix IE11 preloading logic in hlsjs when playing live

modules/KalturaSupport/kalturaIframeClass.php
Can be overridden via flashvar/uiconf by setting attribute
forceCompatMode.
forceCompatMode = none will disable the X-UA-Compatible tag all
together.
Other possible values are as described in MSDN docs.
See
http://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-u
a-compatible-content-ie-edge-do for more info.
FEC-5854
=> Set default X-UA-Compatible to IE=edge

modules/KalturaSupport/resources/uiConfComponents/playbackRateSelector.js
@OrenMe After a fix the was made here https://github.com/kaltura/mwEmbed/pull/2762 to solve the second playback speed increment on iPad, the playback rate selector stopped working with progressive download when 'serverSpeedPlayback' is enabled. 
Checked and verified that now all is working as expected (http, hds, hls).
=> #SUP-8984 fix playbackRateSelector to work with progressive download

modules/EmbedPlayer/resources/mw.EmbedPlayer.js, modules/EmbedPlayer/resources/mw.EmbedPlayerNativeComponent.js
If flashvar "EmbedPlayer.PreloadNativeComponent" is specified:
1. select native component player even without source
2. call the native readyCallback() even without source.
This allows the SDK to open the player with no entry and wait for playerReady.
=> Allow the native SDK to prefetch player resources.

modules/Hlsjs/resources/hlsjs.js
Seeking event is unbind whenever playback starts so we need to
re-register every time initials is called to reestablish handling of
seek before play.
FEC-6132
=> Register seeking event when initialising hlsjs

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
@OrenMe 
Revert fix from fec-5595 (98c82fa)
=> Fix iOS flavor transition jumps back to the video beginning for a split second

modules/KalturaSupport/apiServices/mweApiGetLicenseData.php
JSON_UNESCAPED_SLASHES only exists since php v5.4.0, and some production servers run v5.3.x.
v2.48 also needs this patch (but v2.47 does not).
=> Fix getLicenseData on php < 5.4.0.

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
When we pressed play after back to live, mwEmbedPlayer:: play() was adding a spinner because isTimeUpdateSupported returned true.
syncCurrentTime interval never hides the spinner because currentTime always equals player time (both 0).
Seems like in non-dvr live streams time update is not relevant and for that we need to define isTimeUpdateSupported to return false in such cases.
=> Fixing isTimeUpdateSupported in non-dvr live streams

modules/KalturaSupport/components/dualScreen/display.js, modules/KalturaSupport/components/dualScreen/dualScreen.js, modules/KalturaSupport/components/dualScreen/streamUtils.js, modules/KalturaSupport/components/dualScreen/tests/index.html
* FEC-6431: Lecture capture audio stream - Slides are not displayed at
all on iPad
* FEC-6436: Dual video: if open fullscreen with opened Moderation, secondary screen location is wrong
=> Dual screen fixes

modules/KalturaSupport/components/dualScreen/nativePlayer.js
FEC-6451: Dual video doesn't works on MAC safari - browser error appears
* Use native HLS in Safari
=> Fix FEC-6451

modules/KalturaSupport/components/dualScreen/dualScreen.js, modules/KalturaSupport/components/streamSelector.js, modules/Quiz/resources/IVQApiCall.js, modules/Quiz/resources/quiz.js
Don't reload quiz cuepoints when a stream change occurs
Needed for the dual-video cases in which only the parent media contains
quiz metadata
=> FEC-6441: Fix IVQ for DualVideo players

modules/KalturaSupport/components/dualScreen/dualScreenControlBar.js
FEC-6462: DualScreen - on Safari dragging an item has an offset
* Make the helper absolutely positioned in order to prevent the parent
container to grow
=> Fix FEC-6462

modules/KalturaSupport/resources/uiConfComponents/playbackRateSelector.js
@OrenMe only FF has different hotkeys, tested on all browsers.
=> SUP-9932 playbackRateSelector key code not working on Firefox

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
@OrenMe Sat with Dan and we fixed the logic of the selectDefaultCaption, it would set a CC track to showing and we had 2 CC tracks in showing state (The other one is from the AV player when a user selects a CC) so it would not show any CC.
=> Sup 9616 default language key var not passed to apple AVplayer

modules/KalturaSupport/EntryResult.php
Cache is done by entryId, but response from API depends on protocol as
well, so need to add cache by protocol as well as entry Id
=> Cache entry data by protocol(SUP-11246)

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
When YoutUbe player is loaded it takes time until YT player API is loaded.
If we have ad configured and it fails to load then the player tries to continue the playback on the player.
Due to timing issues the YT player API might not be ready yet and then the call to getCurrentTime on it fails and it blows up the player.
Test page: http://www.radio24.ch/events/mark-forster-131346703
fixes #3494
=> fix(FEC-7049): YT playback fails when ad load fails and there's autoplay

modules/KalturaSupport/components/dualScreen/dualScreen.js, modules/KalturaSupport/components/streamSelector.js
@eitanavgil I talked with Karin about the keyboardShortcutsMap override and she said to remove the open close menu for the stream selector and to change the 'next state' and 'switch views' to 'z' and 'x'
=> SUP-11400 Change dual screen and stream selector keyboardShortcutsMap

modules/KalturaSupport/components/playlistAPI.js, modules/KalturaSupport/resources/mw.KBaseMediaList.js, modules/KalturaSupport/tests/PlaylistOnPageMultiple.qunit.html
* Add new QUnit test page for the feature
* Split '.onpagePlaylistInterface' removal logic depending on 'clipListTargetId' availability
* Cache selector to clipListTarget
* Explicitly specify parent element when adding/removing the 'active' class
=> FEC-7048: Playlist on page doesn't work with multiple embeds on same page

modules/RaptMedia/resources/mw.RaptMedia.js
Pass through the configured googleAnalytics urchin code to allow the Rapt Media engine to track analytics to a customers GA account.
=> [Rapt Media] Pass GoogleAnalytics UA property to Rapt Media engine

modules/KalturaSupport/components/playlistAPI.js
@OrenMe Confirmed that TR do not use ads so we do not need to address that issue now, they are the only customer who uses live stream with playlist player.
=> SUP-11568 Playlist controls are disabled when switching from VOD to live

modules/RaptMedia/resources/mw.RaptMedia.js
Attempt to fix autoplay issues with Rapt Media interactive videos.
- During the initial seek (trigger by "loading" the initial media) prevent the default stopAfterSeek and allow the player to use it's default behavior.
- Prevent hiding of the poster from the initial "loading" seek.
Known Issues:
- The player seems to trigger the `checkPlayerSourcesEvent` _before_ loading the Rapt Media plugin. This means the player doesn't properly wait for the engine to be ready before beginning playback. On slow connections this can cause a stutter at the beginning of playback. It may be causing further race conditions or hiding other issues.
=> [Rapt Media] Improve autoplay and poster display

modules/Hlsjs/resources/hlsjs.js
hls.js sets mode="showing" for text track which is set as default in the manifest.
when not using native/embedded captions we don't want this to happen so set mode="hidden" right after hls.js sets the mode.
=> fix(SUP-12010): fix double captions with hls.js

modules/Dash/resources/dash.js
throwing recovarable errors causes player UI to show error message although Shaka can still recover
=> feat: only throw critical Shaka errors

modules/DoubleClick/resources/mw.DoubleClick.js
@OrenMe  Please review PR, The noticeMessage only appears for preroll and now it will show for all ads. I confirmed on my end that it works with pre mid and post.
=> fix(SUP-12496): ad noticeMessage appears only for preroll

modules/Chromecast/resources/receiver/app_components/ReceiverAdsMgr.js
Add onEndedDone to verify media session will end anyway.
=> fix(FEC-7470, FEC-7471): Receiver app hangs at the end when Pre roll Ad is not enabled

modules/Hlsjs/resources/hlsjs.js, modules/KalturaSupport/components/live/liveCore.js
2 issues here: 
- the live promise rejected after the media has been changed
- the `liveStreamStatusMonitor` interval not cleared on 'live to live' switching
=> SUP-12518 #comment handle switch between offline live entry to vod

modules/DoubleClick/resources/mw.DoubleClick.js
Always let the IMA SDK to restoreCustomPlaybackStateOnAdBreakComplete
=> fix(FEC-6644): after midroll first frame of the video is shown instead of continuing from the stopping point

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
both IMA and YT Iframe API use the global window `onYouTubeIframeAPIReady` and IMA may over run it and cause our YT player's `onYouTubeIframeAPIReady` to not be called.
Use `onYouTubePlayerAPIReady` instead which is called in same place in youtube code anyway :-)
Added some code cleaning as well, but in any case need to clean things up as all flash code is not relevant anymore
=> FEC-7267(fix): fix IMA and YT Iframe API collision

modules/KalturaSupport/components/audioSelector.js
* Add the `dropdown-menu` class to the menu element
=> Fix audio selector icon drops down when clicked

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
This will be part of 2.66, do not merge to 2.65!
=> fix(FEC-7725): parse native tracks on loadedmetadata event

modules/KalturaSupport/resources/mw.ClosedCaptions.js
@OrenMe Please review PR, adding the destroy to the onChangeMedia did not work.
=> fix(SUP-13105): Rebuild CC menu on change media with external CC

modules/KalturaSupport/resources/mw.KAnalytics.js
the best way to know in the player if a plugin is active is to verify that the plugins container contains the class instance, otherwise it's undefined
=> fix: detect if kAnalony is active

modules/Chromecast/resources/sender/mw.EmbedPlayerChromecast.js
We want to check for proxyData value of the chromecast plugin config, 
but `getConfig` of mw.EmbedPlayerChromecast caused an error since it does not have `getConfig` API (this is not a plugin).
Instead, I'm using `getKalturaConfig` API to query the proxyData value of the chromecast plugin config.
=> fix(chromecast): proxyData getter

modules/Chromecast/resources/receiver/mw.EmbedPlayerChromecastReceiver.js
Fix HLS Casting - using MPEG_TS, fix HLS audio tracks parsing due to MPEG_TS change audio tracks mime type comes as video/mpt2t and it broke the logic
In Dash Casting the audio language came as numbers - fixed it to come as languae code and translate the language code to default Display Language
=> SUP-13238 - fix cast lang/audio tracks parsing for android Expanded controller

modules/Quiz/resources/IVQModule.js
use banSeekManager if add status for it in Editor
=> supporting banSeekManager plugin from Editor

modules/KalturaSupport/EntryResult.php
Causes immediate invalidation of every entry object in cache for every request.
Validated both with on disk and memcache cache backend
=> operator is not valid for PHP string concatenation

modules/KalturaSupport/resources/mw.kAnalony.js
2 fixes here - first is when we have an ad and we live - the player state will be playing so add a check if this is the firstplay send the event, 2nd fix is when we live look at the current time of the video element since the logic current time is 0
=> fix: kava live support

modules/EmbedPlayer/resources/mw.MediaElement.js
@OrenMe Please review PR for 2.68, I made the fix as a flag since only a few customers complained about this, as a flag it is a less risky then to add it to everyone and then run into customer's that have manifest that do not have cors-headers and then the playback will not work.
=> fix(SUP-13649): Flag to add Crossorigin to player iframe

modules/KalturaSupport/resources/mw.ClosedCaptions.js
@OrenMe Please review for 2.68, There is no need for layout below with embedded CC as they do not use the allocated space and they are added to the shadow DOM.
=> fix(SUP-13714): Disable below layout with embedded CC

modules/DoubleClick/resources/mw.DoubleClick.js
when using programmatic ad rule midrolls via `mediaProxy.entryCuePoints` then we don't populate the plugin config object adTagUrl and the condition to resume to previous time after midroll depends on it.
What we do is set the instance `this.adTagUrl` so add it to the check.
=> fix(SUP-14668): restore time after ad rule midroll on iOS

modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
The condition used to return `undefined` cause `this.getPlayer().getRawKalturaConfig('playlistAPI', 'autoPlay')` returns undefined if not set
=> fix(FEC-8418): unmute button always shows

modules/KalturaSupport/resources/mw.kAnalony.js
@OrenMe Please review this PR.
I removed the encodeURI functions from the Kanalony code
=> FEC 8433 v2 kanalony referrer is double escaped

modules/KalturaSupport/resources/mw.kAnalony.js
@OrenMe Please review this PR.
Per our F2F and verifying the matter with Eran K I have removed the quarterly play events from resetting upon replaying\seeing the entry,
As a result the drop-off calculations of (#playThrough events / 4) / (#plays) should be corrected.
=> fix(SUP-14960): Moved the quarterly play events flags to the onChangeMedia function

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js, modules/KalturaSupport/resources/mw.ClosedCaptions.js
* revert https://github.com/kaltura/mwEmbed/pull/3895 since `closedCaptions.useCookie` should be `false `in ios player
* This change enables us to config `closedCaptions.useCookie: false` and still enjoy the user preferences which saved by the browser.
=> support default language selection natively (by ios browser)

includes/DefaultSettings.php, modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js, modules/KalturaSupport/resources/mw.ClosedCaptions.js
handle the default language selection natively in `mw.EmbedPlayerNative.js` instead of in `mw.ClosedCaptions.js`
=> fix(FEC-8485): support default language selection natively (by ios browser)

modules/MwEmbedSupport/mediawiki/mediawiki.client.js
Google have apparently broken the user agent scheme in Android 9 user agent.
It used to be X.Y.Z, e.g. 4.2.2, 8.0.0 but in Android 9 it's simply one digit version number now.
Android 9 UA:
Android 8 UA:
=> fix(SUP-15426): user Agent not recognising Android v9

modules/Hlsjs/resources/hlsjs.js
HLS.js renamed their level switch events to LEVEL_SWITCHING and LEVEL_SWITCHED ([see here](https://github.com/video-dev/hls.js/blob/master/docs/API.md))
=> Rename HLS.js level switch events

modules/DoubleClick/resources/mw.DoubleClick.js
@itaykinnrot @OrenMe 
Per Itay's suggestion, I have relocated the saveTimeWhenSwitchMedia from the preroll function to the initiation settings, the issue stems from use cases if a preroll is not set, the saveTimeWhenSwitchMedia will never trigger, therefore, restarts the with entry.
=> fix(FEC-8538): Addressed the issue when a entry restarts after a midroll when preroll is not set

modules/Hlsjs/Hlsjs.json, modules/Hlsjs/resources/Polyfill_Set.js
@OrenMe @itaykinnrot 
We have added a Polyfill that addressed the issue on IE 11 Doc 10 mode when the HLS.JS is crashing. As the "Set" syntax is not supported on IE 10 and below.
=> Fix(SUP-15668): Fix the compatibility issues with IE 11 Doc mode 10

modules/KalturaSupport/resources/mw.kAnalony.js
@OrenMe 
This issue was a regression bug of  FEC-8456.
Fix:
1. Added the onPlayStatus and set it to false on the Default config.
2. And added it to the PLAY count logic.
3. Altered the RESUME count logic to trigger when the currentState is not "PLAY" that to avoid any miscounts.
=> fix(SUP-15645): play event is counted twice in KAVA once a pre-roll is triggered first

modules/EmbedPlayer/resources/mw.EmbedPlayer.js, modules/KalturaSupport/resources/mw.KWidgetSupport.js, modules/KalturaSupport/resources/mw.kAnalony.js
use it in kanalony reprots as the unique id and remove the addition of player counter
=> feat(FEC-8659): reset session id on every media change

modules/Chromecast/resources/sender/chromecast.js
For some reason, Chrome appends script to a player's iframe parent document unless specified explicitly. For more info, see the ticket.
=> PSVAMB-4560: Chromecast nested iframes issue

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
@OrenMe 
Per our F2F, It seems that the previous PR (https://github.com/kaltura/mwEmbed/pull/3922) was not aligned with the current version,
In addition please note, that we are still experiencing some issue with the seek as the entry restarts upon the end of the ads, I believe that it is related to the IMA SDK bug.
=> fix(FEC-8545): issue with seek ios

modules/KalturaSupport/resources/mw.kAnalony.js
use the replay counter to know if to report percentile events and if to report view events.
=> fix(FEC-8577): fail to report view events on media replay

modules/Hlsjs/resources/hlsjs.js
Seems to be a regression of FEC-8210.
Change the "hidden" parameter to "disabled".
=> SUP-16282 VTT/DFXP captions are showing when cc is off

modules/MwEmbedSupport/mediawiki/mediawiki.client.js, modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
@dan-ziv @OrenMe 
Please review this PR.
1. Copied the isNativeIOSPlayback function from ClosedCaption.js and added it to the unMutedOverlayButton.
2. Added a !isNativeIOSPlayback condition to the mobileAutoPlay.
=> Fix(SUP-15794): Issue with the "Unmute" button showing on Native IOS Player

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
The canAutoPlay function is still trying to autoPlay in the Native IOS Player however fails due to the player not being inline, that is why the thumbnails are not showing when the autoPlay and mobileAutoPlay are set to true.
The fix is to add the original return autoplay without the isMuted() function to the if isiPhone validation and I have also added && mw.getConfig("EmbedPlayer.WebKitPlaysInline") !== true ) for safety mesurs.
=> SUP-16617 - thumbnails are not showing in IOS

modules/DoubleClick/resources/mw.DoubleClick.js
The issue was with the `getAdContainer` not appending to the adCover when iOS is set to WebKitPlaysInline=true
=> fix(FEC-8501): iOS Scrubber is disabled after selecting 'learn more' on ad

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js, modules/MwEmbedSupport/mediawiki/mediawiki.client.js, modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
Added Support to the new autoPlay policy in Firefox 66.
https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/
=> feat(FEC-8884): Support muted autoplay policies on Firefox

modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
destroy super does unbind and also remove so no need to implement the method, which causes the bug in playlist player anyway where the indication doesn't go away after user clicks on playlist
=> fix: unmute doesn't get destroyed in playlist player

modules/Hlsjs/resources/hlsjs.js
Fixed the issue when the live streams are erroring in non-DVR live events and as a result, are not recovering. 
1. Added the `this.hls.stopLoad();` when `liveOffline` is called.  
2. Added an additional condition to 'onLiveOnline' function when is non-DVR that will startLoad on the default `startPosition` which is -1 when returning to live.
Tested this on my local environment.
=> fix(FEC-7899): spinning wheel when returning to live

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
Added set Volume to 0 to comply with the AutoMute policies with YouTube entries.
=> fix(FEC-8989): YouTube entires are stuck on endless spinner when on autoPlay

modules/KalturaSupport/components/sourceSelector.js, modules/KalturaSupport/resources/mw.ClosedCaptions.js
In some use cases, streamSelectors and ClosedCaption are rendering empty sources (undefined) as small empty spaces on the drop-down menu.
=> fix(SUP 17081): undefined sources are added to sourceSelector menu as empty spaces

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
Added isIPad checker to the interface update, in case `EmbedPlayer.EnableIpadHTMLControls` config is set to false.
=> fix(FEC-9085): playState is marked as "paused" although playing

modules/Quiz/resources/quiz.js
Fixed the issue with the Save and Clear button, not appearing when clicking on the "Hint" button
=> fix(FEV-314): Save button was disabled upon clicking the hint icon

modules/Quiz/resources/quiz.js
on CP click it seeked 0.5 sec before the question cue-point marker, so in case when video is paused - it seeked 0.5 sec before the CP and stayed paused.
The changes makes sure that when we seek on a question-cue-point it always keeps playing and not paused.
=> FEV-320 - start playing on a question-cue-point click

modules/Quiz/resources/quiz.js
Problem description: 
'Why' bubble appears on feedback page cousin to overlap exit button 
changes:
Hide 'Why' bubble when feedback popup is visible
=> FEV-318 - hide 'Why' bubble when feedback popup is visible

modules/KalturaSupport/resources/mw.ClosedCaptions.js
Added additional line spacing for the default Closed Captioning style in order to support Thai Characters.
=> fix(SUP-18895): Vertical Space is cutting Thai letters

modules/KalturaSupport/components/360/resources/video360.js
Issue with aspect calculation when 360 video is on a playlist, the aspect is miscalculated (includes the hight or width of the playlist) and results in a malformed video display.
The calculation was if the original calculation was less than 1.4, we will set it to 1.4
=> fix(SUP-18987): issue with aspect in 360

modules/Hlsjs/resources/hlsjs.js
need to nudge timeline to cause hlsjs to reinit audio controller, issue referenced at https://github.com/video-dev/hls.js/issues/2323
=> fix(SUP-19347): audio not starting on hls on IE11

modules/Quiz/resources/quiz.js
@einatr 
I've changed the `focus` from the question to the open-area element and that will save the question even if the user clicked the question a second time without changing the answer.
=> fix(SUP-18477): save input if user is clicking of the why button a second time

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
@OrenMe 
We don't reset the hasEnded flag when calling change media, therefore, we do not call setDuration:
https://github.com/kaltura/mwEmbed/blob/master/modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js#L175-L177
=> fix(19550): Duration tag on YT playlists does not update

modules/KalturaSupport/components/live/liveStatus.js
@OrenMe 
It seems that the setLiveStatusButtonDefaultState() is bindded when onChange is getting sent 
(For example: https://github.com/kaltura/mwEmbed/blob/e667d18f51107074fbcdef0c6e5b5e7b543d242a/modules/KalturaSupport/components/related/related.js#L420)
I've added a condition to only apply to LiveStream type entries.
=> fix(SUP-19662): "Off air" string is showing on non-Live entries

kWidget/kWidget.js
@eitanavgil @OrenMe @yairans 
2 major changes
1. The user agent identifier (added a chrome one and added to the condition) which resolves the issue in Chrome.
It seems that when in Chrome we enter this condition due to the fact that "Safari" string is indeed included in the userAgent, see in the below.
> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
Please note, that adding too many userAgent detectors will cause a StackOverflow.
2. For Safari, added the videoDisplay class to the write function which is in charge of the dual-screen display.
=> fix(SUP-18965): Incorrect DualScreen layout with ThumbEmbed

kWidget/kWidget.js, resources/mediawiki/mediawiki.js
@OrenMe 
Per your suggestion I have added a regex check to the inner try.
=> fix(SUP-19782): Player fails when window.location.protocol is not set to http/https

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js, modules/MwEmbedSupport/mediawiki/mediawiki.client.js, modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
@OrenMe 
I made the the iPad on iOS 13 get recognized as a mobile device, see if that is ok.
=> fix(FEC-9386): Unmuted button is not working on iPad iOS13

modules/Hlsjs/resources/hlsjs.js
@OrenMe 
Tested the matter with the LiveStats plugin and the original fix: FEC-6130
is still applicable.
We will have to test it against  the KMS as well.
=> fix(SUP-20040): seek options are not synced

modules/KalturaSupport/resources/mw.ClosedCaptions.js
When seeking, the Native Tracks are not removed.
=> fix(SUP-19930): Captions are showing twice on inline iOS

modules/Hlsjs/resources/hlsjs.js
Encounter the same issue that was occuring on IE 11 on SUP-16960
=> fix(FEC-9507): Live stream audio is not initiated on Edge

modules/KalturaSupport/components/dualScreen/dualScreenControlBar.css
When the DualScreen plugin is turned on, in some cases when the player size is small, we are unable to select from menus (Captions, SpeedSelectors etc).
Example:
https://www.kaltura.com/index.php/extwidget/preview/partner_id/2340551/uiconf_id/41078391/entry_id/0_2azz2r4a/embed/dynamic?&debugKalturaPlayer
=> fix(FEV-437): Unable to select from the menu when dualScreen is on

modules/KalturaSupport/resources/mw.ClosedCaptions.js
When KS is added (KMS for example) to the VTT call the call is sent wrong and a result broken.
Currently:
http://cdnapi.kaltura.com/api_v3/index.php/service/caption_captionasset/action/serveWebVTT/captionAssetId/0_svo0de7e/segmentIndex/-1/version/2/**captions.vtt**/ks/NjdlOTkwMWFkYzNlNTNiMjgyZTczMTBjNWE1MGQ2OGU2OTcyMDExYnw1NDIxMzE7NTQyMTMxOzE1Nzk1MzEwNzY7MjsxNTc5NDQ0Njc2LjY5NDY7YWRtaW47ZGlzYWsdfsdfbGVtZW50Ozs=
With the fix:
http://cdnapi.kaltura.com/api_v3/index.php/service/caption_captionasset/action/serveWebVTT/captionAssetId/0_svo0de7e/segmentIndex/-1/version/2/ks/NjdlOTkwMWFkYzNlNTNiMjgyZTczMTBjNWE1MGQ2OGU2OTcyMDExYnw1NDIxMzE7NTQyMTMxOzE1Nzk1MzEwNzY7MjsxNTc5NDQ0Njc2LjY5NDY7YWRtaW47ZGlzYWJssdfsdfZW50Ozs=/captions.vtt
Basically I moved the captions.vtt of the captions to the end.
=> fix(SUP-20644): VTT not working on iOS when KS is added

modules/DoubleClick/resources/mw.DoubleClick.js
Use case:
When user is implementing an Ad Cue point with a cust_param to the entry on a specific time frame, it does not getting recognized as the adTagUrl is hard coded to only listen to it on the flashvars level.
PS.
I didn't want to remove the original way we recognize the adTag since and just added to it.
=> fix(FEC-9626): adCuePoints do not work with cust_params

modules/KalturaSupport/resources/mw.ClosedCaptions.js
The use-case: we set the `displayCaptions` to true even if the entry does not contains any captions.
I have added the `isCaptionsShown` that will determine if we want to show the captions or not.
Tested with Ads and Bumpers.
=> fix(FEC-9593): Incorrect video size in player containing bumper/Ad

modules/KalturaSupport/resources/mw.KBaseSmartContainer.js
This issue is related to a KMS use case, we do not calculate the height of the SmartContainer icons on iOS correctly and it causing the icons to truncate on iOS only.
=> fix(SUP-21183): Icons are truncated on iPhone

modules/Chromecast/resources/sender/mw.EmbedPlayerChromecast.js
Same issue that we had on V7, we call resume instead of init on Android
=> fix(SUP-21004): Chrome-cast is unable to stream via Android

modules/Hlsjs/resources/hlsjs.js
Do not nudge the playback time when in DVR
=> fix(SUP-21019): Internet Explorer endless spinner in livestreams with DVR

modules/Quiz/resources/quiz.js
The issue is with the way we call `$.cpObject.cpArray` [here](https://github.com/kaltura/mwEmbed/blob/28d148df7d6319cf10fee9360c0b1b34cedfb515/modules/Quiz/resources/quiz.js#L1165), this function is called before we initiate $.cpObject.cpArray [here](https://github.com/kaltura/mwEmbed/blob/c6c2f5d988d08a405abb862f1669c80e783f8351/modules/Quiz/resources/IVQModule.js#L270)  
I was able to observe the above while printing the content of them, using breakpoints will actually won't show the issue.
=> fix(KMS-20622): Quiz bubbles are not showing when retaking quiz

modules/EmbedPlayer/resources/mw.FullScreenManager.js
Tested the matter, and this is not a regression, I was able to reproduce this issue on older player versions as well.
=> fix(SUP-21282): No native fullscreen on iPad 12 and above

modules/Quiz/resources/quiz.js
We never addressed the use case of reflection points when we are unable to skip
=> fix(KMS-20600): cannot submit quiz when having a Reflection Point at the end of it

modules/Quiz/resources/quiz.js
1. I have made it so now we can alter from the hint and question more than once with the setTime on the focus not returning undefined.
2. The original bug when the FE is saving the answer even though we didn't click save.
=> fix(KMS-19979): Saves answer after edit for open-question

modules/EmbedPlayer/resources/mw.FullScreenManager.js
When `mw.getConfig('EmbedPlayer.EnableIpadNativeFullscreen` is set to true, it will affect also none iPad devices.
Regression fix of:
https://github.com/kaltura/mwEmbed/pull/4140
=> fix(SUP-21601): Fullscreen is native when on desktop

kWidget/kWidget.js
replace `success/error` to `done/fail` see https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax
This changed is required only in the embed code since the player itself is running in an iframe and uses own its own jquery (1.11.1)
=> fix(FEC-10114): jquery 3.0 breaks the player

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
Due to changes on FEC-9424 we need to send 'playing' on the Yt analytics in order to pass PLAY and RESUME event.
=> fix(SUP-22116): Play Analytics not getting send for YT entries

modules/KalturaSupport/resources/mw.kAnalony.js
The Quartile marks are no longer sending due to the removal of the old analytics in FEC-10004.
=> fix(SUP-22818): Player is not sending Quartile marks

modules/Quiz/resources/quiz.js
@eitanavgil 
The quiz.css and the quizFonts.css are only available when we are on debugKalturaPlayer mode, which can explain why I was unable to see this issue while debugging locally, so basically the entire logic of the initial fix is not applicable so no reason to have this fix.
=> fix(FEV-772): reverted SUP-16764

modules/KalturaSupport/components/dualScreen/dualScreen.js
@eitanavgil 
The textTrack on the second screen should be disabled as well.
=> fix(SUP-24147):  player displaying captions for entry even if the captions plugin is disabled

modules/EmbedPlayer/resources/mw.EmbedPlayerImageOverlay.js
When entering a full screen and the entry is type of image- the image remains static according to its dimensions, rather than stretch according to full screen dimensions.
solution: in embedPlayerHTML func- updating the image only if the image hasn't been loaded yet.
Solves [FEC-11111](https://kaltura.atlassian.net/browse/FEC-11111).
=> fix(FEC-11111): images remain static according to their dimensions

modules/KalturaSupport/resources/mw.kAnalony.js
changed in kAnalony to fire event 14 (100% viewed) at 100% (instead of 99%).
=> fix(FEC-11135): video duration differences affects Analytics completion rate

modules/Quiz/resources/quiz.js
Issue:
in IVQ, when in submit mode or review mode, can't reach "continue" button using "tab" in keybaord.
Solution: 
changing tabindex=6.3 to tabindex=5 in continue btn element.
Solves FEC-11158
=> fix(FEC-11158): accessibility in Video quiz - can't reach continue button using keyboard

modules/KalturaSupport/resources/mw.KBaseMediaList.js
issue:
when playing entry using playlist player and exiting full screen - empty playlist container is displayed.
solution:
calculating width of playback only if there are playlists in the playlistSet.
Solves FEC-11239
=> fix(FEC-11239): black bars upon exiting full screen

kWidget/kWidget.js
the issue:
when playing media in IOS and captureClickEventForIOS flag is set to true, the native ios controls are not working.
when captureClickEventForIOS flag is set to true, there is re-writing of the video element. seems like "videoDisplay" div was forgotten and as a result, the hierarchy in DOM was changed.
the solution:
added videoDisplay div before video element, so the hierarchy will be the same as when the flag is disabled.
=> fix(FEC-11256): video controls are not clickable on IOS when captureClickEventForiOS flag is used

modules/KalturaSupport/resources/mw.ClosedCaptions.js
issue:
when creating a playlist and for some of the entries in it the "DisplayOnPlayer" for the captions is disabled, and you move from an entry with DisplayOnPlayer=true to an entry with DisplayOnPlayer=false - the captions of previous entry show up on current entry and kind of stuck.
The expected behavior is to not show captions at all and btn of CC also should not be displayed.
solution:
as part of the flow, adding a callback([]) with empty captions array.
Solves FEC-11252.
=> fix(FEC-11252): caption with displayOnPlayer off doesn't work properly in playlist

modules/KalturaSupport/components/cvaa/cvaa.js, modules/KalturaSupport/components/cvaa/cvaa.tmpl.html, modules/TimedText/TimedText.i18n.json
**issue:**
some texts in cvaa template don't have translation keys.
**solution:**
added the following keys and used them when is needed:
- "mwe-cvaa-advancedOptions": "Advanced options"
- "mwe-cvaa-customCaptions": "Custom captions"
- "mwe-cvaa-sizeTitle": "Size"
- "mwe-cvaa-colorTitle": "Color"
- "mwe-cvaa-fontTitle": "Font"
- "mwe-cvaa-backgroundTitle": "Background"
- "mwe-cvaa-captionsPreview": "Captions preview"
- "mwe-cvaa-editCustomCaptions": "Edit custom captions"
Solves FEC-11264
=> fix(FEC-11264): accessibility - missing some translation keys in cvaa template

modules/KalturaSupport/resources/mw.ClosedCaptions.js
Issue:
when setting the captions layout to "below video" and playing .vtt captions- the captions are placed on the video as "on top" layout, instead of inside the container below the video.
Solution:
forcing inset=0 when layout=below video. In addition, added position=relative to parent class so captions will be placed according to the caption container and not to the video holder.
Solves FEC-11271
=> fix(FEC-11271):displaying .VTT captions not working properly for below video layout

modules/Quiz/resources/css/quiz.css
Changes approved by Ido Achrak
=> fix(FEC-11232): styles for "I understand" button

modules/QnA/resources/qna.js
**issue:**
when qna.onPage=false and the qna is enabled via the webcasting app, there is an empty black container, instead of the qna layout. The reason for this behavior is that the display att of the relevant element stays with "none" value, and never being changed to "block".
**solution:**
adding call to show() on the relevant element where needed.
Solves FEC-11373
=> fix(FEC-11373): blank space in QnA area when onPage is false

modules/KalturaSupport/components/chapters/chapters.css, modules/KalturaSupport/components/chapters/chapters.js
1) use css property "visibility: hidden" to prevent tabbing into closed sidebar panel;
2) handle "home"\"end" keys for navigation to first\last chapter(slide)
=> fix(SUP-28319): prevent focus chapters when side panel closed

modules/KalturaSupport/components/playPauseBtn.js, skins/kdark/css/layout.css
**the issue:**
when in fullscreen, tooltips of bottom bar buttons are not displayed.
**solution:**
increase z-index of tooltips to 9999, as player ins fullscreen is having z-index=9999.
also had to delay the focus of play/pause btn when entering fullscreen, to prevent from the tooltip to appear in a wrong place.
Solves FEC-11542
=> fix(FEC-11542): tooltips in full screen don't pop out when hovering over it

skins/kdark/css/layout.css
**the issue:**
some playback rate options are overlaid by dual screen menu and can't be chosen.
**solution:**
moving z-index from .controlBarContainer.hover to .controlBarContainer css class.
Solves FEC-11713
=> fix(FEC-11713): playback rate options are overlaid by dual screen menu

modules/KalturaSupport/components/dualScreen/dualScreen.css
**the issue:**
when using the mouse to hover away from the player, the contrast shadow of dual screen controls doesn't disappear.
**solution:**
there is a css that is handling this scenario, however the style is not applied. removing "*" from .dualscreen.componentOff
Solves FEC-11774
=> fix(FEC-11774): dual screen constant shadowed layer appears

modules/KalturaSupport/components/share/share.js
**description of the issue:**
when share plugin is enabled for the player, the share url is not being sanitized, which exposes a security vulnerability.
sanitizing encoded and decoded share url.
Solves FEC-11791
=> fix(FEC-11791): share url has cross-site scripting vulnerability

modules/KalturaSupport/components/dualScreen/dualScreen.js
**the issue:**
when autoplay=true and secondary video has embedded captions, the embedded captions are still shown on player.
**solution:**
hide embedded captions from secondary screen when loadedmetadata event is triggered.
Solves FEC-11831
=> fix(FEC-11831): embedded captions in dual screen are shown when autoPlay is true

modules/EmbedPlayer/resources/mw.EmbedPlayer.js, modules/QnA/resources/qna.js
**the issue:**
this is a regression caused by SUP-11362.
when uivar Kaltura.ForceLayoutRedraw=true and using qna plugin where onPage=false, the qna container is not visible when the player is loaded.
executing the responsive action that was added by SUP-11362 only in 2 cases:
1. when there is no qna plugin/disabled.
2. if qna plugin exists and enabled, then only when onPage=true.
Solves FEC-11887
=> fix(FEC-11887): qna container is not visible on embedded player by default if the uivar “Kaltura.ForceLayoutRedraw” is set to true

modules/Dash/resources/dash.js
**the issue:**
when trying to play dash on ios it fails with "unsupported source type" error from shaka.
player v2 version 2.86 was upgrading shaka version from 2.3.2 to 2.5.19.
according to the following link [isBrowserSupported for iOSTYPE: QUESTION](https://github.com/google/shaka-player/issues/2100) shaka returned false for isBrowserSupported on ios, then on version 2.5 isBrowserSupported() returned true for ios.
**solution:**
add !isIOS when registering shaka.
Solves FEC-11992
=> fix(FEC-11992): v2 - Unsupported source type error received on iPhone when using shaka

modules/WebcastPolls/resources/webcastPolls.js
**the issue:**
the scenario:
1. presenter is creating poll
2. users are voting
3. presenter clicks on hide via webcasting app
4. presenter clicks on show via webcasting app
expected behavior -> player displays the correct amount of responses (totalVoters)
observed behavior -> player is displaying 0 responses
player is not saving poll-results cuepoints, which contains the total voters value. since hide is resetting the local data, when clicking on show, the player is displaying 0 responses.
when player is receiving poll-results cuepoint, we should save it.
Solves FEC-12016
=> fix(FEC-12016): poll responses is showing 0 after toggling between the 'Hide/Show' button within the Webcasting App

modules/WebcastPolls/resources/webcastPolls.js
**the issue:**
following a fix in [FEC-12016](https://github.com/kaltura/mwEmbed/pull/4259) , slides do not appear in dualscreen in the recorded VOD.
**solution:**
call fixLiveCuePointArray and updateCuePoints only if in live state.
Solves FEC-12080
=> fix(FEC-12080): slides do not appear in dual screen in VOD webcast

modules/KalturaSupport/resources/mw.KBaseMediaList.js
**the issue:**
chapters show wrong thumbnail. when clicking on a thumbnail, we jump to a point in the video where the thumbnail is different from the chapter's thumbnail.
player is doing parseInt to time/1000, therefore, the time is less accurate (i.e. 118.123 becomes 118). in V7 we send time/1000 w/o parsing it to int or changing the value.
**solution:**
remove parseInt and leave the time value as accurate as it can be.
Solves FEC-12183
=> fix(FEC-12183): chapter and slides have wrong thumbnails

modules/KalturaSupport/resources/mw.ClosedCaptions.js
**the issue:**
vtt captions are not shown in playlist player when dualscreen plugin is enabled.
dualscreen plugin is creating a DOM element which is "pushing" down the captions. unlike srt, vtt has inset values and the player is rendering vtt captions differently than srt. the dualscreen related DOM element doesn't affect the srt captions.
**solution:**
set position=absolute on captionsOverlay, when rendering vtt. this way the captionsOverlay container will not be interfered by other elements. 
Solves FEC-12182
=> fix(FEC-12182): playlist player not showing VTT captions when dualscreen plugin is enabled

modules/KalturaSupport/resources/mw.ClosedCaptions.js
**the issue:** 
when player's bottom bar controls has hover mode enable and the captions are vtt type, the bottom bar is overlaying the captions. 
**the solution:** 
when hover mode in enable and closed caption's layout is ontop, changing some css attributes which  allows the captions to behave as expected.
solves FEC-12230
=> fix(FEC-12230): VTT Captions are covered up by player controls when Hover mode enabled

includes/DefaultSettings.php
ignore non valid hostname in HTTP_X_FORWARDED_HOST header (same regex as [the server](https://github.com/kaltura/server/blob/Rigel-18.6.0/infra/storage/file_transfer_managers/asperaMgr.class.php#L81))
=> fix(FEC-12267): Fix XSS Vulnerability in mwEmbed - enforce valid domain format

docs/content_api.php
**the issue:**
there is a mismatch between the documentation and what actually happens; callback function do not pass "id" parameter, but only the time value.
**solution:**
need to remove "id" from the callback function in the documentation.
Solves FEC-11293
=> docs(FEC-12293): update kbind api documentation

modules/KalturaSupport/components/share/share.js
**the issue:** 
Whenever a title of an entry is including ampersand (&) in it, the generated New e-mail is cutting everything after that symbol.
encoding entry name
solves FEC-12265
=> fix(FEC-12265): v2 Share button generates mostly blank email, due to Ampersand

modules/KalturaSupport/EntryResult.php, modules/KalturaSupport/resources/mw.KWidgetSupport.js
**the issue:**
when entry is scheduling not for now the message "out of scheduling" appear even in the kmc or passing ks admin.
if there is ks admin the message "out of scheduling" doesn't appear and the entry plays as expected.
solves FEC-12319
=> fix(FEC-12319): player showing out of schedule message even there is admin ks

modules/KalturaSupport/RequestHelper.php
add alternatives to getReferer logic.
**the issue:**
in some cases, OSs/browsers, for example, OS X/Safari, will not pass $_SERVER['HTTP_REFERER'] and then the fallback would be 'http://www.kaltura.com/'. If a customer is using an ACP where certain domains are allowed (excluding kaltura.com) and the browser did not pass the HTTP_REFERER, then the player will display an error.
**solution:**
add alternatives to get/create the referer.
Solves FEC-12322
=> fix(FEC-12322): add alternatives to getReferer logic

modules/MwEmbedSupport/mediawiki/mediawiki.client.js
**the issue:**
when using iframe embed in Android/Chrome -> the fullscreen does not work.
in mediawiki we check for android chrome version, since the regex matches only versions with 2 digits,for new Chrome version (100+) which have 3 digits, the player thinks it's an old one. example: for Chrome/102.0.0.0 the regex returns version "10" instead of "102".
**solution:**
change regex to also fit 3 digits versions.
Solves FEC-12328
=> fix(FEC-12328): android fullscreen not working using iframe embed

modules/KalturaSupport/components/share/share.js
**the issue:**
when use a custom socialShareUrl with query parameter at the end of the url, the linkedin share popup cut out the query parameters. 
**the solation:**
added encoding for the linkedin share url.
solves FEC-12332
=> fix(FEC-12332): video share to LinkedIn cut out the query parameters

modules/EmbedPlayer/resources/mw.EmbedPlayerNative.js
**the issue:**
safari native player is not setting to false the audioTrack.enabled of the first item in audioTracks list.
**solution:**
disable all audioTracks before setting current one to enable.
Solves FEC-12371
=> fix(FEC-12371): multiaudio with live does not switch back to first audio track in Safari

skins/kdark/css/layout.css
**the issue:**
on focus mode (using tab) the scrubber has the native design of the browser and not the kaltura design(blue border)
adding CSS to scrubber:focus element.
solves FEC-12404
=> fix(FEC-12404): Scrubber has the native design of the browser and not the design of Kaltura

modules/unMuteOverlayButton/resources/unMuteOverlayButton.js
**background:**
when using bumper plugin, there is an option to configure a url that will be opened in a new window, whenever clicking on the bumper video.
**the issue:**
when configuring an adUrl in bumper plugin, clicking on the unmuteOverlayButton will open the url in a new window. expected behavior is to only do the unmute, without opening the ad url.
**the root cause:**
the videoHolder element is listening to the adClick event; the unmuteOverlayButton is a child element of videoHolder, hence, whenever clicking on the unmute button the adClick event is being triggered and a new window with the configured url is being opened.
**solution:**
bind the unmuteOverlayButton to the adClick event and stop propagation.
Solves FEC-12512
=> fix(FEC-12512): unmute button opens the ad url when using Bumper

modules/KalturaSupport/resources/mw.KWidgetSupport.js
**context:**
adding a fallback option upon inaccessible API Gateway.
BE are adding new property to `KalturaAccessControlModifyRequestHostRegexAction` named `checkAliveTimeoutMs` - see ref [here](https://www.kaltura.com/api_v3/testmeDoc/objects/KalturaAccessControlModifyRequestHostRegexAction.html), which defines the timeout duration for checking the ip.
**solution:**
- when the new property `checkAliveTimeoutMs` is defined and its value is bigger than 0, an ajax call to the serviceUrl is being made.
- the URLs replacement will occur only if the connection succeeded or `checkAliveTimeoutMs` is 0, null, negative number.
- in case `checkAliveTimeoutMs` is a valid value (bigger than 0) and the ajax call has failed, we are not overriding the urls.
**description of changes:**
- add async ajax …
=> feat(FEC-12521): fallback option upon inaccessible API Gateway

modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js
**the issue:**
when click on the player element to play the video (not click on the play buttons) the video play well but the time counter and the seekbar is stuck and doesn't move.
**the root cause:** 
the monitor function is called only when play the video from the buttons.
call to the monitor function when the video is playing, not matter how the video is turn on.
=> fix(FEC-12575): YouTube entries time counter issue
